# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'v2MagicalRecord' do
  pod 'MagicalRecord'
end

target 'v2MagicalRecordTests' do

end

target 'v2MagicalRecordUITests' do

end

