# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

target 'NeeNeeApp' do
  pod 'MagicalRecord'
end

target 'NeeNeeAppTests' do

end

target 'NeeNeeAppUITests' do


end
