(function(){var Style=function(){return{setProperty:function(a,c,b,d){d?a.setProperty(c,b,"important"):a.setProperty(c,b);return a}}}();String.prototype.startsWith||Object.defineProperty(String.prototype,"startsWith",{enumerable:!1,configurable:!1,writable:!1,value:function(a,c){c=c||0;return this.lastIndexOf(a,c)===c}});
String.prototype.endsWith||Object.defineProperty(String.prototype,"endsWith",{value:function(a,c){var b=this.toString();if(void 0===c||c>b.length)c=b.length;c-=a.length;b=b.indexOf(a,c);return-1!==b&&b===c}});
var Css3=function(){return{tapHighlightColor:function(a,c,b){Style.setProperty(a,"-webkit-tap-highlight-color",c,b)},transitionProperty:function(a,c,b){Style.setProperty(a,"transition-property",c,b);Style.setProperty(a,"-webkit-transition-property",c,b);Style.setProperty(a,"-moz-transition-property",c,b);Style.setProperty(a,"-ms-transition-property",c,b);Style.setProperty(a,"-o-transition-property",c,b)},transitionDuration:function(a,c,b){Style.setProperty(a,"transition-duration",c,b);Style.setProperty(a,
"-webkit-transition-duration",c,b);Style.setProperty(a,"-moz-transition-duration",c,b);Style.setProperty(a,"-ms-transition-duration",c,b);Style.setProperty(a,"-o-transition-duration",c,b)},transitionTimingFunction:function(a,c,b){Style.setProperty(a,"transition-timing-function",c,b);Style.setProperty(a,"-webkit-transition-timing-function",c,b);Style.setProperty(a,"-moz-transition-timing-function",c,b);Style.setProperty(a,"-ms-transition-timing-function",c,b);Style.setProperty(a,"-o-transition-timing-function",
c,b)},transformOrigin:function(a,c,b){Style.setProperty(a,"transform-origin",c,b);Style.setProperty(a,"-webkit-transform-origin",c,b);Style.setProperty(a,"-moz-transform-origin",c,b);Style.setProperty(a,"-ms-transform-origin",c,b);Style.setProperty(a,"-o-transform-origin",c,b)},transform:function(a,c,b){Style.setProperty(a,"transform",c,b);Style.setProperty(a,"-webkit-transform",c,b);Style.setProperty(a,"-moz-transform",c,b);Style.setProperty(a,"-ms-transform",c,b);Style.setProperty(a,"-o-transform",
c,b)},backgroundLinearGradient:function(a,c,b,d){Style.setProperty(a,"background","-webkit-gradient(linear, left top, left bottom, from("+c+"), to("+b+"))",d);Style.setProperty(a,"background","-moz-linear-gradient(top, "+c+", "+b+")",d)}}}(),AMOAD_AD_DOMAIN="d.amoad.com",AMOAD_CLICK_DOMAIN="d.amoad.com",AMOAD_JS_DOMAIN="j.amoad.com",AMOAD_JS_VERSION="3.2.0",AMOAD_API_DOMAIN="api1.amoad.com",AMOAD_API_PATH="/ad/jsonp/?",Utils=function(){var a=function(a,c){return b(a,new RegExp("(?:^|;[ ]*)"+c+"=([^;]*)"))},
c=function(a,c){return b(a,new RegExp("(?:^|[?&])"+c+"=([^&]*)"))},b=function(a,b){if(!a||!b)return"";var c=b.exec(a);return c&&2<=c.length&&c[1]?c[1]:""},d={getDomain:function(a){return(a=a.match(/^(.*?:\/\/)(.*?)([a-z0-9][a-z0-9\-]{1,63}\.[a-z\.]{2,6})[\:[0-9]*]?([\/].*?)?$/i))&&3<=a.length?a[3]:""},getNowDate:function(){return new Date},setCookieValue:function(a,b,c,d,n,g){a&&void 0!==a.cookie&&b&&(b=encodeURIComponent(b)+"=",c&&(b+=encodeURIComponent(c)),d&&(b+="; max-age="+d),n&&(b+="; domain="+
n),g&&(b+="; path="+g),a.cookie=b)},culcRandom:function(){return Math.floor(99999999999*Math.random())}};d.getCookie=a;d.getCookieValue=function(b,c){return decodeURIComponent(a(b,c))};d.getCsKeyValue=function(a,c){return b(a,new RegExp("(?:^|,[ ]*)"+c+"=([^,]*)"))};d.getJsQuery=c;d.getJsQueryValue=function(a,b){return decodeURIComponent(c(a,b))};d.getKeyValue=b;return d}(),Uuid=function(){var a={3:/^[0-9A-F]{8}-[0-9A-F]{4}-3[0-9A-F]{3}-[0-9A-F]{4}-[0-9A-F]{12}$/i,4:/^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/i,
5:/^[0-9A-F]{8}-[0-9A-F]{4}-5[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/i,all:/^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$/i};return{isUUID:function(c,b){var d=a[b?b:"all"];return d&&d.test(c)}}}(),Dom=function(){var a="https:"===document.location.protocol?!0:!1,c=a?"https:":"http:",b=window.location.hostname,d=window.location.href,e=b.match(/.*ameblo\.jp$/)||b.match(/.*ameba\.jp$/)||b.match(/.*candy\.am$/)?!0:!1,h=b.match(/.*mbga\.jp$/)?!0:!1,k="http://"+AMOAD_CLICK_DOMAIN+"/click/?cid=",
m=/iPhone/.test(navigator.userAgent)?!0:!1,n=/iPad/.test(navigator.userAgent)?!0:!1,g=m||n?!0:!1,l=/Android/.test(navigator.userAgent)?!0:!1,t=g||l?!0:!1,v=document,p=g&&!/Safari/.test(navigator.userAgent)?!0:!1,q;/iP(hone|od|ad)/.test(navigator.platform)?(q=navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/),q=[parseInt(q[1],10),parseInt(q[2],10),parseInt(q[3]||0,10)]):q=null;var s=m&&320<screen.width&&375>=screen.width?!0:!1,w=m&&375<screen.width?!0:!1,f={};f.LOCATION_IS_SSL=a;f.LOCATION_PROTOCOL=
c;f.LOCATION_HOSTNAME=b;f.LOCATION_HOSTNAME_IS_AMEBA=e;f.LOCATION_HOSTNAME_IS_MOBAGE=h;f.LOCATION_HREF=d;f.CLICK_URL_HEAD=k;f.USERAGENT_IS_IPHONE=m;f.USERAGENT_IS_IPAD=n;f.USERAGENT_IS_IOS=g;f.USERAGENT_IS_ANDROID=l;f.USERAGENT_IS_SMARTPHONE=t;f.DEVICE_IS_IPHONE_6=s;f.DEVICE_IS_IPHONE_6_PLUS=w;f.DOCUMENT=v;f.USERAGENT_IS_IOS_WEBVIEW=p;f.IOS_VERS=q;return f}(),Node=function(){var a=function(a){return document.createElement(a)},c=function(a){return document.getElementById(a)},b=function(a){for(var b=
a.childNodes.length-1;0<=b;b--)a.removeChild(a.childNodes[b])},d=function(a,b){a.setAttribute(b,"");a.removeAttribute(b)},e=function(a){return!a||0>=a.length?[]:Array.prototype.slice.call(a)},h={};h.create=a;h.resetStyle=function(a){a.style.margin="0";a.style.padding="0";a.style.border="none";return a};h.getHead=function(){return document.getElementsByTagName("head")[0]};h.buildScript=function(b,c,d){var e=a("script");d&&(e.id=d);e.src=b;e.type="text/javascript";e.async=c?!0:!1;return e};h.buildImgTag=
function(b,c){var d=a("img");c&&(d.id=c);d.src=b;d.width=1;d.height=1;return d};h.appendChild=function(a,b){a.appendChild(b)};h.appendHeadChild=function(a){Node.appendChild(Node.getHead(),a)};h.existForId=function(a){return document.getElementById(a)?!0:!1};h.getById=c;h.setGlobal=function(a,b){window[a]=b};h.getGlobal=function(a){return window[a]};h.clearChildren=b;h.createOrReplaceById=function(k,e){var n=c(k);n?(b(n),d(n,"style")):(n=a(e),n.id=k);return n};h.listToArray=e;h.nodesByClassName=function(a,
b){return e(a.getElementsByClassName(b))};h.nodesByTagName=function(a,b){return e(a.getElementsByTagName(b))};h.nodesFilterAttr=function(a,b,c){return a.filter(function(a){return a.getAttribute(b)===c},this)};h.appendSidNodeChild=function(a,b){"SCRIPT"===a.tagName?a.parentNode.insertBefore(b,a):a.appendChild(b)};h.removeAttribute=d;return h}(),Cookie=function(){return{getValue:function(a){return Utils.getCookieValue(document.cookie,a)},setValue:function(a,c,b,d,e){void 0===d&&(d=(d=Utils.getDomain(document.location.href))?
d:document.location.hostname);void 0===e&&(e="/");Utils.setCookieValue(document,a,c,b,d,e)}}}(),Impression=function(){var a=function(a){a&&((new Image(1,1)).src=a)},c={DELAY_MIN:500,DELAY_MAX:4E3,DELAY_DEFAULT:1E3,asyncSend:function(b,c){b&&0<c&&setTimeout(function(){a(b)},c)}};c.syncSend=a;c.delayMillis=function(a){return a&&a.impDelayMillis?Math.min(Math.max(a.impDelayMillis,500),4E3):1E3};c.bannerUrl=function(a){if(a){if(a.imp)return a.imp;if(a.ads&&a.ads[0].imp)return a.ads[0].imp}return null};
c.nativeUrl=function(a){return a&&a.NATIVE_IMP_URL?a.NATIVE_IMP_URL:null};return c}(),Window=function(){try{var a=window.top.location.protocol===window.location.protocol&&window.top.location.hostname===window.location.hostname&&window.top.location.port===window.location.port?window.top:window}catch(c){a=window}var b={};b.top=a;return b}(),AdTag=function(){var a=function(a){return Node.nodesByClassName(a,"ad_frame").concat(Node.nodesByClassName(a,"amoad_frame"))},c=function(a,b){return a?a.hasAttribute(b):
!1},b=function(a,b){return a?a.getAttribute(b):null},d=function(a,b,c){return a?a.setAttribute(b,c):null},e=function(a){return c(a,"data-sid")},h=function(a){return b(a,"data-sid")},k=function(a,b,c){return a?a.getAttribute(b)===c?!0:!1:!1},m={DATA_SID:"data-sid"};m.amoadFrames=a;m.sidNodes=function(b,c){return a(b).filter(function(a){return e(a)&&h(a)===c||-1!==a.className.indexOf("sid_"+c)})};m.hasAttr=c;m.getValue=b;m.setValue=d;m.getIntValue=function(a,c){return parseInt(b(a,c),10)};m.getPercentValue=
function(a,c){var d=b(a,c);return d&&-1!==d.indexOf("%")?parseInt(d,10)/100:-1};m.hasSid=e;m.getSid=h;m.setSid=function(a,b){return d(a,"data-sid",b)};m.firstChildValue=function(c,d){if(!c)return null;for(var k=null,t=a(c),v=0;v<t.length&&!(k=b(t[v],d));v++);return k};m.isValue=k;m.everyChildIsValue=function(b,c,d){if(!b)return!1;b=a(b);return 0>=b.length?!1:b.every(function(a){return k(a,c,d)})};m.valuesExist=function(a,b,c){if(!a)return null;a=a.split(c);var d=b.split(c);return a.some(function(a){return d.some(function(b){return a===
b})})};m.valueAsFunction=function(a){if(!a)return null;a=a.split(".");var b=Node.getGlobal(a[0]);if(!b)return null;for(var c=1,d=a.length;c<d;c++)if(b=b[a[c]],!b)return null;return"function"===typeof b?b:null};return m}(),AdTagStatus=function(){var a={none:0,scanned:1,sent:2,received:3,done:4},c=function(a){return a?(a=a.getAttribute("data-amoad-status"))?a:"":""},b=function(a,b){a&&b&&a.setAttribute("data-amoad-status",b)},d=function(b){return b?a[b]:0},e=function(a){if(!a||0>=a.length)return[];
if(1===a.length)return a;a=a.slice(0);a.sort(function(a,b){return d(c(a))-d(c(b))});return a},h=function(a,b){if(!a||0>=a.length)return null;var e=null;a.some(function(a){return d(c(a))>=b?(e=a,!0):!1});return e};return{isScanned:function(a){return 1<=d(c(a))},isSent:function(a){return 2<=d(c(a))},isReceived:function(a){return 3<=d(c(a))},isDone:function(a){return 4<=d(c(a))},setScanned:function(a){b(a,"scanned")},setSent:function(a){b(a,"sent")},setReceived:function(a){b(a,"received")},setDone:function(a){b(a,
"done")},findNone:function(a,b){var e=null;a.some(function(a){return 0==d(c(a))?(e=a,!0):!1});return e},findScannedBySid:function(a,b){return h(e(AdTag.sidNodes(a,b)),1)},findSentBySid:function(a,b){return h(e(AdTag.sidNodes(a,b)),2)},findReceivedBySid:function(a,b){return h(e(AdTag.sidNodes(a,b)),3)},findDoneBySid:function(a,b){return h(e(AdTag.sidNodes(a,b)),4)}}}(),AdTagRta=function(a){this.isNone=AdTag.isValue(a,"data-rta","none")};
AdTagRta.everyChildIsNone=function(a){return AdTag.everyChildIsValue(a,"data-rta","none")};var AdTagSeg=function(a){this.ids=AdTag.getValue(a,"data-seg-id");this.callback=AdTag.getValue(a,"data-seg-callback")};AdTagSeg.prototype.segIdExist=function(a){return AdTag.valuesExist(this.ids,a,"|")};AdTagSeg.prototype.asyncCallback=function(){var a=AdTag.valueAsFunction(this.callback);a&&setTimeout(function(){a.call(this)},300)};
var AdTagDmp=function(a){this.isNone=AdTag.isValue(a,"data-dmp","none")},AdTagStyle=function(a){this.width=AdTag.getValue(a,"data-style-width");this.height=AdTag.getValue(a,"data-style-height");this.float_=AdTag.getValue(a,"data-style-float");var c=AdTag.getPercentValue(a,"data-style-scale");this.scale=0.8<=c&&1>c||0.7===c?c:null;this.important=AdTag.hasAttr(a,"data-style-important");this.responsive=Dom.USERAGENT_IS_IPAD?!1:AdTag.hasAttr(a,"data-style-responsive");this.overlay={};this.overlay.clickRotation=
AdTag.hasAttr(a,"data-style-overlay-click-rotation");this.overlay.rigid=AdTag.hasAttr(a,"data-style-overlay-rigid");this.overlay.ease=AdTag.hasAttr(a,"data-style-overlay-ease");this.overlay.pr=Dom.USERAGENT_IS_IOS?AdTag.hasAttr(a,"data-style-overlay-pr"):!1};AdTagStyle.OVERLAY_CLICK_ROTATION_FLG_NAME="__com_amoad_overlay_click_rotation";
var AdTagIdfa=function(a){a=AdTag.getValue(a,"data-idfa");this.id=Uuid.isUUID(a)?a:null},AdTagRequest=function(a){this.toAdSpot=AdTag.hasAttr(a,"data-request-to-ad-spot")},AdTagTest=function(a){this.mode=Number(AdTag.firstChildValue(Dom.DOCUMENT,"data-test-mode"));switch(this.mode){case 1:Dom.USERAGENT_IS_SMARTPHONE=!0;Dom.USERAGENT_IS_IOS=!0;Dom.USERAGENT_IS_ANDROID=!1;break;case 2:Dom.USERAGENT_IS_SMARTPHONE=!0,Dom.USERAGENT_IS_IOS=!1,Dom.USERAGENT_IS_ANDROID=!0}},AdTagAnalytics=function(a){this.reportId=
AdTag.getValue(a,"data-analytics-report-id")},AdTagLink=function(a){this.url=AdTag.getValue(a,"data-link")},AdTagClick=function(a){this.params=AdTag.getValue(a,"data-click-params")},AdTagOption=function(a){this.analytics=new AdTagAnalytics(a);this.click=new AdTagClick(a);this.dmp=new AdTagDmp(a);this.rta=new AdTagRta(a);this.idfa=new AdTagIdfa(a);this.request=new AdTagRequest(a);this.seg=new AdTagSeg(a);this.style=new AdTagStyle(a);this.link=new AdTagLink(a);this.test=new AdTagTest(a)},DmpSegs=function(){return{dmpToAmSegsStr:function(a,
c,b,d,e){return a.sort(function(a,c){var d;if(d=a[b]){var e=c[b];d=e?e-d:-1}else d=1;return d}).map(function(a){a=(a=a[c])?d[a]:null;return a}).filter(function(a){return a?!0:!1}).slice(0,e).join("|")}}}(),Fox=function(){var a=function(a){Cookie.setValue("amoad_fox_called2","true",86400);a&&Object.keys(a).length&&a.segs&&"number"===typeof a.segs.length&&0<a.segs.length&&(Node.setGlobal("__amoadFoxJsonCallBack",function(b){Cookie.setValue("amoad_fox_request_segs",DmpSegs.dmpToAmSegsStr(a.segs,"seg_id",
"ts",b,300),2592E3)}),Node.appendHeadChild(Node.buildScript("http://j.amoad.com/js/fox.json",!0,"amoad_fox_json")))},c=function(){return Node.existForId("amoad_fox_loader")||Cookie.getValue("amoad_fox_called2")?!1:!0},b={dmpCall:function(){Node.setGlobal("__amoadFoxCallBack",a);Node.appendHeadChild(Node.buildScript("http://dmp.app-adforce.jp/ad/i/rta?_pcd=aa&_method=window%2e__amoadFoxCallBack",!0,"amoad_fox_loader"))}};b.reconfirmCall=c;b.shouldCall=function(){return!Dom.LOCATION_IS_SSL&&c()?!0:
!1};b.shouldRequest=function(){return!0};b.getRequestCookie=function(){return Cookie.getValue("amoad_fox_request_segs")};return b}(),DeNA=function(){var a=function(a){Cookie.setValue("amoad_dena_called2","true",86400);a&&Object.keys(a).length&&a.segs&&"number"===typeof a.segs.length&&0<a.segs.length&&(Node.setGlobal("__amoadDeNAJsonCallBack",function(b){Cookie.setValue("amoad_dena_request_segs",DmpSegs.dmpToAmSegsStr(a.segs,"seg_id","ts",b,300),2592E3)}),Node.appendHeadChild(Node.buildScript("http://j.amoad.com/js/dena.json",
!0,"amoad_dena_json")),Dynalyst.denaSend(a.segs))},c=function(){return Node.existForId("amoad_dena_loader")||Cookie.getValue("amoad_dena_called2")?!1:!0},b={dmpCall:function(){Node.setGlobal("__amoadDeNACallBack",a);Node.appendHeadChild(Node.buildScript("http://ad_rta.sp.mbga.jp/_api_amoad_segment?cb=__amoadDeNACallBack",!0,"amoad_dena_loader"))}};b.reconfirmCall=c;b.shouldCall=function(){return!Dom.LOCATION_IS_SSL&&c()?!0:!1};b.shouldRequest=function(){return!0};b.getRequestCookie=function(){return Cookie.getValue("amoad_dena_request_segs")};
return b}(),Dynalyst=function(){var a=encodeURIComponent("FINAL FANTASY Record Keeper(RTA)"),c=["44","36","7","4"],b="",d=!0;Dom.USERAGENT_IS_IOS?b="_IOS":Dom.USERAGENT_IS_ANDROID?b="_ANDROID":d=!1;var e=function(b,c,d,e){b=b+"?an="+a+"&advid=1256&cty=JPN&tz=JST&dtype="+d+"&uq="+e+"&restype=gif&ext="+encodeURIComponent('{"category":"'+c+'"}');(new Image(1,1)).src=b},h={denaSend:function(a){if(d)for(var h=0;h<c.length;h++)for(var n=c[h],g=0;g<a.length;g++){var l=a[g].seg_id;if(l==n){l+=b;Cookie.getValue("amoad_dynalyst_request_seg")!=
l&&(a=Utils.culcRandom(),e("http://dynalyst-mk.adtdp.com/site/game/ext",l,"1",a),e("http://mk.ca-conv.amoad.com/site/game/ext",l,"2",a));Cookie.setValue("amoad_dynalyst_request_seg",l,2592E3);return}}}};h.beaconSend=e;return h}(),RightSegment=function(){var a=function(a){Cookie.setValue("amoad_rs_called2","true",86400);a&&Object.keys(a).length&&a.segments&&"number"===typeof a.segments.length&&0<a.segments.length&&(Node.setGlobal("__amoadRsJsonCallBack",function(b){Cookie.setValue("amoad_rs_request_segs",
DmpSegs.dmpToAmSegsStr(a.segments,"seg_key","epoch",b,300),2592E3)}),Node.appendHeadChild(Node.buildScript("http://j.amoad.com/js/rs.json",!0,"amoad_rs_json")))},c=function(){return Node.existForId("amoad_rs_loader")||Cookie.getValue("amoad_rs_called2")?!1:!0},b={dmpCall:function(){Node.setGlobal("__amoadRsCallBack",a);Node.appendHeadChild(Node.buildScript("http://rs-ap.adtdp.com/rta/?pid=bac2ea9ceb76beba&callback=__amoadRsCallBack",!0,"amoad_rs_loader"))}};b.reconfirmCall=c;b.shouldCall=function(){return!Dom.LOCATION_IS_SSL&&
c()?!0:!1};b.shouldRequest=function(){return!0};b.getRequestCookie=function(){return Cookie.getValue("amoad_rs_request_segs")};return b}(),Criteo=function(){var a=[["crta_amoad_(?:ios_)*300250.*;","Q0x.0.1H2"],["crta_amoad_(?:ios_)*32050.*;","Q0x.0.1GG"],["crta_aa_deco_300250.*;","Q0x.0.1J2"]],c=[["crta_aa_amb_(?:ios_)*32050.*;","Q0x.0.1Gz"],["crta_aa_amb_300100.*;","Q0x.0.1J1"]],b=[["crta_aa_mbg_(?:ios_)*32050.*;","Q0x.0.1H0"]];return{LOADER_ID:"amoad_criteo_rta",buildLoader:function(a,b,c){a=Dom.LOCATION_PROTOCOL+
"//rtax.criteo.com/delivery/rta/rta.js?netId="+escape("2490")+"&cookieName="+escape("crtg_amoad_rta")+"&rnd="+a.call(this)+"&varName="+escape("crtg_content");b=b.call(this,"script");b.type="text/javascript";b.id="amoad_criteo_rta";b.src=a;b.async=c;return b},segsOfContent:function(d){if(!d)return"";var e=[];Dom.LOCATION_HOSTNAME_IS_MOBAGE?b.map(function(a){(new RegExp(a[0])).test(d)&&e.push(a[1])}):Dom.LOCATION_HOSTNAME_IS_AMEBA?c.map(function(a){(new RegExp(a[0])).test(d)&&e.push(a[1])}):a.map(function(a){(new RegExp(a[0])).test(d)&&
e.push(a[1])});return e.join("|")}}}(),InfoMarker=function(){var a=Dom.LOCATION_PROTOCOL+"//i.amoad.com/creatives/shared/icon_i_l_w.png",c=Dom.LOCATION_PROTOCOL+"//i.amoad.com/creatives/shared/icon_i_ads_w.png",b=function(a,b){var c=a.style;Css3.transitionDuration(c,"0ms",b);Style.setProperty(c,"margin","0px",b);Style.setProperty(c,"padding","0px",b);Style.setProperty(c,"border","none",b);Style.setProperty(c,"position","absolute",b);Style.setProperty(c,"top","0px",b);Style.setProperty(c,"width","76px",
b);Style.setProperty(c,"height","20px",b);Style.setProperty(c,"z-index","777",b);Style.setProperty(c,"background-color","transparent",b);Css3.transitionProperty(c,"all",b);Css3.tapHighlightColor(c,"rgba(0,0,0,0)",b);d(a,b)},d=function(a,b){var c=a.style;Css3.transitionDuration(c,"0ms",b);Style.setProperty(c,"right","-56px",b)},e=function(a,b){var c=a.style;Css3.transitionDuration(c,"300ms",b);Style.setProperty(c,"right","0px",b)},h=function(a,b){var c=a.style;Css3.transitionDuration(c,"0ms",b);Style.setProperty(c,
"margin","0px",b);Style.setProperty(c,"padding","0px",b);Style.setProperty(c,"border","none",b);Style.setProperty(c,"position","absolute",b);Style.setProperty(c,"top","0px",b);Style.setProperty(c,"background-repeat","no-repeat",b);Style.setProperty(c,"background-size","contain",b);Style.setProperty(c,"background-color","transparent",b);k(a,b)},k=function(b,c){var d=b.style;Css3.transitionDuration(d,"0ms",c);Style.setProperty(d,"right","56px",c);Style.setProperty(d,"width","14px",c);Style.setProperty(d,
"height","14px",c);Style.setProperty(d,"background-image","url("+a+")",c)},m=function(a,b){var d=a.style;Css3.transitionDuration(d,"300ms",b);Style.setProperty(d,"background-image","url("+c+")",b);Style.setProperty(d,"right","0px",b);Style.setProperty(d,"width","70px",b);Style.setProperty(d,"height","14px",b)},n=function(a,b){var c=a.style;Css3.transitionDuration(c,"0ms",b);Style.setProperty(c,"margin","0px",b);Style.setProperty(c,"padding","0px",b);Style.setProperty(c,"border","none",b);Style.setProperty(c,
"position","absolute",b);Style.setProperty(c,"top","0px",b);Style.setProperty(c,"width","76px",b);Style.setProperty(c,"height","20px",b);Style.setProperty(c,"background-color","transparent",b);Style.setProperty(c,"right","0px",b);Style.setProperty(c,"z-index","777",b);Style.setProperty(c,"display","none",b);a.href="http://d.amoad.com/guideline/";a.target="_blank";a.addEventListener("click",function(b){b.stopPropagation();Dom.USERAGENT_IS_IOS_WEBVIEW||(b.preventDefault(),window.open(a.href,a.target))},
!1);g(a,b)},g=function(a,b){var c=a.style;Css3.transitionDuration(c,"0ms",b);Style.setProperty(c,"display","none",b)},l=function(a,b){var c=a.style;Css3.transitionDuration(c,"300ms",b);Style.setProperty(c,"display","block",b)};return{images:function(a,c,p,q){b(a,q);h(c,q);n(p,q);p.addEventListener("touchstart",function(a){a.stopPropagation()},!1);p.addEventListener("touchend",function(a){a.stopPropagation()},!1);a.addEventListener("touchstart",function(a){a.stopPropagation()},!1);a.addEventListener("touchend",
function(a){a.stopPropagation()},!1);a.addEventListener("click",function(b){b.preventDefault();b.stopPropagation();e(a,q);m(c,q);l(p,q);setTimeout(function(){d(a,q);k(c,q);setTimeout(function(){g(p,q)},250)},3E3)},!1);a.appendChild(c);return[a,p]}}}(),DirectStore=function(a,c,b){this.appId=a;this.beacon=c;this.href=b?"itms-apps://itunes.apple.com/app/id"+a:"market://details?id="+a};DirectStore.prototype.sendClick=function(){this.beacon&&((new Image(1,1)).src=this.beacon)};
var Scale=function(a){var c=function(a){if(a||Scale.window===Scale.window.top)if(Dom.USERAGENT_IS_ANDROID)if(a=Scale.window.innerWidth,a>Scale.window.innerHeight){var b=Math.max(Scale.screen.width,Scale.screen.height),c=Math.min(Scale.screen.width,Scale.screen.height);a=Math.max(b>=1.5*a?c*a/b:c,320)}else b=Math.min(Scale.screen.width,Scale.screen.height),Math.max(Scale.screen.width,Scale.screen.height),a=Math.max(b>=1.5*a?b*a/b:b,320);else{if(Dom.USERAGENT_IS_IPAD)return 400*Scale.window.innerWidth/
Scale.screen.width;a=Scale.screen.width}else a=0;return a?a:320},b=function(a){return c(a)/320},d={};d.window=a;d.screen=a.screen;d.BASE_WIDTH=320;d.BASE_WIDTH_OLD_ANDROID=320;d.windowWidth=c;d.responsiveScale=b;d.responsiveSize=function(a,c,d){d=b(d);return{width:a*d,height:c*d}};return d}(window),Content=function(){var a=function(a,b){var c=a.style,d=b.style.important;Style.setProperty(c,"border","none",d);Style.setProperty(c,"margin","0",d);Style.setProperty(c,"padding","0",d);return c},c=function(a,
b){a.addEventListener("touchstart",function(a){a.stopPropagation();b.style.overlay.clickRotation&&Node.setGlobal(AdTagStyle.OVERLAY_CLICK_ROTATION_FLG_NAME,!0)},!1);a.addEventListener("touchend",function(a){a.stopPropagation()},!1);a.addEventListener("scroll",function(a){a.stopPropagation()},!1)},b=function(a,b){return a.useDirectStore?function(c,d){return e(a.appId,c,d,b)}:function(a,c){return d(a,c,b)}},d=function(a,b,c){var d=document.createElement("a");d.target="_blank";d.href=b.click.params?
a+"&"+b.click.params:a;Style.setProperty(d.style,"text-decoration","none",c);Dom.USERAGENT_IS_IOS_WEBVIEW||(d.onclick=function(){window.open(this.href,this.target);return!1});return d},e=function(a,b,c,d){var l=new DirectStore(a,b,Dom.USERAGENT_IS_IOS);a=document.createElement("a");a.target="_blank";a.href=c.click.params?l.href+"&"+c.click.params:l.href;Style.setProperty(a.style,"text-decoration","none",d);a.onclick=function(){l.sendClick();window.open(this.href,this.target);return!1};return a},h=
function(b,c){var d=Node.create("img"),f=a(d,c);d.src=b;d.alt="";var l=c.style.important;Style.setProperty(f,"float","left",l);Style.setProperty(f,"margin-left","5px",l);Style.setProperty(f,"margin-top","6px",l);Style.setProperty(f,"width","38px",l);Style.setProperty(f,"height","38px",l);return d},k=function(b,c,d){c=Node.create("div");var f=a(c,d);c.innerHTML=decodeURIComponent(b);d=d.style.important;Style.setProperty(f,"float","left",d);Style.setProperty(f,"margin-left","5px",d);Style.setProperty(f,
"margin-top","6px",d);Style.setProperty(f,"width","250px",d);Style.setProperty(f,"height","38px",d);Style.setProperty(f,"font-weight","500",d);Style.setProperty(f,"text-align","left",d);Style.setProperty(f,"word-wrap","break-word",d);Style.setProperty(f,"word-break","break-all",d);for(var l=0,e=0,h=b.length;e<h;e++)l=4>escape(b.charAt(e)).length?l+0.7:l+1;b=l;l=250;12*b>l&&(l*=2);b=Math.floor(l/b);b=Math.min(b,29);fontSize=b=Math.max(b,9);Style.setProperty(f,"color","color",d);Style.setProperty(f,
"font-size",fontSize+"px",d);Style.setProperty(f,"line-height",fontSize+4+"px",d);return c},m=function(b,c){var d=Node.create("div"),f=a(d,c);d.innerHTML="ads by AMoAd";var l=c.style.important;Style.setProperty(f,"position","absolute",l);Style.setProperty(f,"bottom","1px",l);Style.setProperty(f,"right","5px",l);Style.setProperty(f,"font-weight","400",l);Style.setProperty(f,"text-align","left",l);f.color=b;f.fontSize="9px";f.lineHeight="9px";return d},n=function(a,b){return a.useDirectStore?function(c,
d){g(c,b,a.appId)}:function(a,c){l(a,b,c)}},g=function(a,b,c){Node.nodesByTagName(a,"a").filter(function(a){return a.href&&0===a.href.indexOf(b)}).map(function(a){var b=new DirectStore(c,a.href,Dom.USERAGENT_IS_IOS);a.href=b.href;Node.removeAttribute(a,"onclick");a.onclick=function(){b.sendClick();window.open(b.href,"_blank");return!1}})},l=function(a,b,c){Node.nodesByTagName(a,"a").filter(function(a){return a.href&&0===a.href.indexOf(b)}).map(function(a){Node.removeAttribute(a,"onclick");a.href=
c.click.params?a.href+"&"+c.click.params:a.href;Dom.USERAGENT_IS_IOS_WEBVIEW||(a.onclick=function(){window.open(a.href,"_blank");return!1})})},t=function(b,d,l,f){var e=Node.create("iframe");d=a(e,f);setTimeout(function(){var a=b.replace(/\+/g," ");e.contentDocument.writeln(decodeURIComponent(a));e.contentDocument.close();l(e.contentDocument,f)},0);var h=f.style.important;Style.setProperty(d,"position","relative",h);Style.setProperty(d,"display","block",h);Style.setProperty(d,"width","100%",h);Style.setProperty(d,
"height","100%",h);c(e,f);return e},v=function(b,d,l,f){var e=Node.create("iframe");d=a(e,f);e.src=b;setTimeout(function(){l(e.contentDocument,f)},0);b=f.style.important;Style.setProperty(d,"position","relative",b);Style.setProperty(d,"display","block",b);Style.setProperty(d,"width","100%",b);Style.setProperty(d,"height","100%",b);c(e,f);return e},p={create:function(d,l,e,f,p){var g=null,u="giftext"===d?l.ads[0]:l;switch(d){case "img":g=u.src;e=Node.create("img");f=a(e,p);e.src=g;e.alt="";g=p.style.important;
Style.setProperty(f,"position","relative",g);Style.setProperty(f,"display","block",g);Style.setProperty(f,"width","100%",g);Style.setProperty(f,"height","100%",g);Style.setProperty(f,"box-shadow","rgb(0, 0, 0) 0 0 3px",g);c(e,p);g=b(u)(u.href,p);g.appendChild(e);break;case "giftext":f=u.src;g=u.title;l=l.nolicense;d=parseInt(e[2].substring(1,3),16);var B=parseInt(e[2].substring(3,5),16),C=parseInt(e[2].substring(5,7),16),z=Node.create("div"),x=a(z,p),y=p.style.important;Style.setProperty(x,"position",
"relative",y);Style.setProperty(x,"display","block",y);Style.setProperty(x,"width","100%",y);Style.setProperty(x,"height","100%",y);Style.setProperty(x,"box-shadow","rgb(0, 0, 0) 0 0 3px",y);Style.setProperty(x,"border-top-left-radius","3px",y);Style.setProperty(x,"border-bottom-left-radius","3px",y);Style.setProperty(x,"border-bottom-right-radius","3px",y);Css3.backgroundLinearGradient(x,"rgb("+d+", "+B+", "+C+")","rgba("+d+", "+B+", "+C+", 0.9)",y);f&&Node.appendChild(z,h(f,p));g&&Node.appendChild(z,
k(g,e[0],p));l||Node.appendChild(z,m(e[1],p));c(z,p);e=z;g=b(u)(u.href,p);g.appendChild(e);break;case "html":e=n(u,Dom.CLICK_URL_HEAD),g=u.html?t(u.html,f,e,p):v(u.iframeLocation,f,e,p)}return g},prAnchorCreate:function(b,l){var e=Node.create("div"),f=a(e,l);Style.setProperty(f,"height",ContentOverlay.PR_HEIGHT+"px",!1);Style.setProperty(f,"text-align","center",!1);Style.setProperty(f,"background-color","#000",!1);Style.setProperty(f,"color","#fff",!1);Style.setProperty(f,"line-height",ContentOverlay.PR_HEIGHT+
"px",!1);Style.setProperty(f,"font-size","12px",!1);Style.setProperty(f,"width","100%",!1);Style.setProperty(f,"position","relative",!1);Style.setProperty(f,"text-decoration","none",!1);Css3.tapHighlightColor(f,"rgba(0,0,0,0)",!1);c(e,l);f=new Image;f.src="http://stg-i.amoad.net/creatives/shared/pr.png";var h=f.style;Style.setProperty(h,"position","relative",!0);Style.setProperty(h,"margin","5px 0",!0);Style.setProperty(h,"height","16px",!0);e.appendChild(f);return b?(f=d(b,l),f.appendChild(e),f):
e}};p.anchorCreatorForAd=b;p.htmlConverterForAd=n;return p}(),ContentOverlay=function(){var a=function(a,b){a.display=b?"block":"none"},c=function(b,c,e,h,g,m,n,f){document.addEventListener("touchstart",function(){a(b,!1);e&&Node.getGlobal(AdTagStyle.OVERLAY_CLICK_ROTATION_FLG_NAME)&&(Node.setGlobal(AdTagStyle.OVERLAY_CLICK_ROTATION_FLG_NAME,!1),e.call(this))},!1);document.addEventListener("touchend",function(){c?(a(b,!0),d(b,c,h,g,m,n,f)):setTimeout(function(){a(b,!0);d(b,c,h,g,m,n,f)},1E3)},!1);
if(Dom.USERAGENT_IS_ANDROID){var k;document.addEventListener("scroll",function(){k&&clearTimeout(k);a(b,!1);k=setTimeout(function(){k=null;a(b,!0);d(b,c,h,g,m,n,f)},1E3)},!1)}},b=function(a,b,c,d,g,m){document.addEventListener("scroll",function(){var k=e(b);(a.top?"top":"bottom")!==k&&(g&&(a.height="bottom"===k?m+28/c+"px":m+"px"),h(a,d,c,k,!0))},!1)},d=function(a,b,c,d,g,m,k){c=g?c:e(c);(g=(a.top?"top":"bottom")!==c)&&m&&(a.height="bottom"===c?k+28/d+"px":k+"px");h(a,b,d,c,g)},e=function(a){return"bottom"===
a?window.pageYOffset+window.innerHeight>Math.max(document.documentElement.scrollHeight,document.body.scrollHeight)-100?"top":"bottom":100>window.pageYOffset?"bottom":"top"},h=function(a,b,c,d,e){c&&e&&(Css3.transitionDuration(a,"0ms"),Css3.transformOrigin(a,"center "+d),Css3.transform(a,"scale("+c+")"));b?k(a,d):m(a,d,e?20:0)},k=function(a,b){Css3.transitionDuration(a,"0ms");a.opacity="0";n(a,b,0);setTimeout(function(){Css3.transitionDuration(a,"3500ms");a.opacity="1"},0)},m=function(a,b,c){Css3.transitionDuration(a,
"0ms");a.opacity="0";n(a,b,c);setTimeout(function(){Css3.transitionDuration(a,"300ms");n(a,b,0);a.opacity="1"},0)},n=function(a,b,c){c||(c=0);a.removeProperty("top");a.removeProperty("bottom");a[b]=c+"px"},g={POS_BOTTOM:"bottom",POS_TOP:"top",PR_HEIGHT:28,overlay:function(a,b,c){var d=a.style;d.position="relative";d.overflow="hidden";d.width=b+"px";d.height=c+"px";d.margin="0 auto";d.padding="0";return a},overlaySpace:function(d,e,h,g,m,k,n,f,A){var r=d.style;r.position="fixed";r.left="0";r.right=
"0";r.width="100%";r.overflow="hidden";r.margin="0";r.padding="0";r.transitionProperty="all";Css3.tapHighlightColor(r,"rgba(0,0,0,0)",!0);r.zIndex="800";a(r,!1);m?k||b(r,g,h,n,f,e):c(r,n,A,g,h,k,f,e);return d}};g.setStyleDisplay=a;g.startAnimation=function(a,b,c,d,g,m,k){b=d?b:e(b);a.height=m&&"bottom"===b?k+28/c+"px":k+"px";h(a,g,c,b,!0)};g.setRotationEvent=function(a,b){var c=function(){document.removeEventListener("touchstart",c,!1);setTimeout(function(){b.call(this)},1E3*a)};document.addEventListener("touchstart",
c,!1)};return g}(),ContentDiv=function(){return{setStyle:function(a,c,b,d){Style.setProperty(a,"visibility","hidden",d);Style.setProperty(a,"position","relative",d);Style.setProperty(a,"overflow","hidden",d);Style.setProperty(a,"width",c,d);Style.setProperty(a,"height",b,d);Style.setProperty(a,"margin","0 auto",d);Css3.tapHighlightColor(a,"rgba(0,0,0,0)",d)},show:function(a,c){Style.setProperty(a,"visibility","visible",c)}}}(),LICENSE_TEXT_SIZE=10,LICENSE_STRING="ads by AMoAd",BLOCK_MARGIN=5,TOP_BLOCK_MARGIN=
5,AMoAdSmartphone={htmlNode:function(a,c,b,d,e,h,k,m){var n=document.createElement("iframe");a=n.style;c=k.style.important;Style.setProperty(a,"position","relative",c);Style.setProperty(a,"border","none",c);k.style.width?Style.setProperty(a,"width",k.style.width,c):Style.setProperty(a,"width",b+"px",c);k.style.height?Style.setProperty(a,"height",k.style.height,c):Style.setProperty(a,"height",d+"px",c);k.style.float_&&Style.setProperty(a,"float",k.style.float_,c);Style.setProperty(a,"margin","0pt auto",
c);Style.setProperty(a,"display","block",c);k.style.scale?(b=k.style.scale,Css3.transformOrigin(a,"left top",c),Css3.transform(a,"scale("+b+")",c)):k.style.responsive&&(b=Scale.responsiveScale(),Css3.transformOrigin(a,"center top",c),Css3.transform(a,"scale("+b+")",c));if(e){var g=decodeURIComponent(e.replace(/\+/g," "));setTimeout(function(){n.contentDocument.writeln(g);n.contentDocument.close();m(n.contentDocument,k)},0)}else n.src=h,setTimeout(function(){m(n.contentDocument,k)},0);return n}};
function SmartphoneEmbedded(){function a(a,c,e,h,k){var m=[],n=e.style.important;if("object"==typeof k)for(var g in k)if("size"==g||"size_overturn"==g)k[g].match(/px|%$/i)||(k[g]+="px");var l=function(e,g){var l=AdTagStatus.findReceivedBySid(document,a);if(l){l.children&&0!=l.childNodes.length||(m=[],c=l);var k=e.height?e.height:e.ads.height,s=e.width?e.width:e.ads.width,l=e.type,w=document.createElement("div");if(g.style.scale){for(var f=c.parentNode,A=null;f&&f!==document.body.parentNode&&null!==
(A=getComputedStyle(f));){var r=A.zoom;if(1<r||1>r){Style.setProperty(c.style,"zoom",1/r,n);break}f=f.parentNode}f=g.style.scale;s=s*f+"px";k=k*f+"px"}else g.style.responsive?(f=Scale.responsiveScale(!0),k=Scale.responsiveSize(s,k),s=k.width+"px",k=k.height+"px"):(f=1,s=g.style.width?g.style.width:s+"px",k=g.style.height?g.style.height:k+"px");ContentDiv.setStyle(w.style,s,k,n);m.push(w);k=Content.create(l,e,h,f,g);w.appendChild(k);"html"!==l&&InfoMarker.images(Node.create("div"),Node.create("div"),
Node.create("a"),!0).map(function(a){w.appendChild(a)});Node.appendSidNodeChild(c,w);Impression.asyncSend(Impression.bannerUrl(e),Impression.delayMillis(e));g.seg.callback&&g.seg.asyncCallback();g.dmp.isNone||(foxCall(),denaCall(),rightSegmentCall());AdTagStatus.setDone(c)}};this.createAd=function(a,b){l(a,b);1<m.length?(ContentDiv.show(m[m.length-1].style,n),c.removeChild(m.shift())):ContentDiv.show(m[m.length-1].style,n)}}var c=[];this.createAd=function(b,d,e,h,k,m){for(var n=!1,g,l=0,t=c.length;l<
t;l++)if(c[l].sid==b){g=c[l].obj;n=!0;break}!1==n&&(g=new a(b,d,h,k,m),c.push({sid:b,obj:g}));g.createAd(e,h)}}
var AdEmbedded=function(){return{createAd:function(a,c,b,d,e,h){(new SmartphoneEmbedded).createAd(a,c,b,d,e,h)}}}(),AdOverlay=function(){return{createAd:function(a,c,b,d,e,h,k){a=b.type;var m=1;if("img"===a){var n=Scale.responsiveSize(b.width,b.height,!0);h=n.width;var g=n.height}else if(h=b.width,g=b.height,"html"===a||"giftext"===a)m=Scale.responsiveScale(!0);var l="HEADER"===b.position?ContentOverlay.POS_TOP:ContentOverlay.POS_BOTTOM,n=b.is_fixed,t=d.style.overlay.rigid,v=d.style.overlay.ease,
p=l==ContentOverlay.POS_BOTTOM&&d.style.overlay.pr,q=Content.create(a,b,e,m,d);if(q){e=ContentOverlay.overlay(Node.create("div"),h,g);e.appendChild(q);"html"!==a&&InfoMarker.images(Node.create("div"),Node.create("div"),Node.create("a"),!0).map(function(a){q.appendChild(a)});var s=ContentOverlay.overlaySpace(Node.createOrReplaceById("ad_cloud_overlay_space","div"),g,m,l,n,t,v,p,k);s.appendChild(e);if(p){switch(a){case "img":var w=b.href;break;case "giftext":w=b.ads[0].href}s.appendChild(Content.prAnchorCreate(w,
d))}Node.appendSidNodeChild(c,s);AdTagStatus.setDone(c);setTimeout(function(){ContentOverlay.startAnimation(s.style,l,m,t,v,p,g);ContentOverlay.setStyleDisplay(s.style,!0)},500);Impression.asyncSend(Impression.bannerUrl(b),Impression.delayMillis(b));d.dmp.isNone||(foxCall(),denaCall(),rightSegmentCall())}}}}(),AdCall=function(){return{buildAdCallJsonP:function(a,c,b){c=c.call(b,"script");c.type="text/javascript";c.charset="utf-8";c.src=a;c.async=!0;return c},modelSegs:function(){return Dom.DEVICE_IS_IPHONE_6?
"Q0x.0.1Jz|Q0x.0.1K0":Dom.DEVICE_IS_IPHONE_6_PLUS?"Q0x.0.1Jz|Q0x.0.1K1":""}}}(),ROTATION_TERM_NONE=99999,callBack=function(a,c){if(a.type){var b=AdTagStatus.findSentBySid(document,c);if(b){AdTagStatus.setReceived(b);var d=new AdTagOption(b),e=getAdTagParams(b),h=void 0!==e.nolicense,k=a.rotation?a.rotation:ROTATION_TERM_NONE,m=e.color?e.color:a.color?a.color.split("-"):"";if(!0==a.is_overlay){if(d.style.overlay.clickRotation)var n=function(){getJsonP(c,b,getRequestURI(c,b,d))};AdOverlay.createAd(c,
b,a,d,m,{fixed:a.is_fixed?a.is_fixed:!1,nolicense:h,position:a.position?a.position:"FOOTER",size:a.height+"px",size_overturn:a.height+"px",ad_base_color:m[2]},n);void 0!==e.rotationterm&&0<e.rotationterm&&(k=e.rotationterm);a.rotation_type&&a.bill_type&&"STOP_CPM"==a.rotation_type&&"CPM"==a.bill_type&&(k=ROTATION_TERM_NONE);k!==ROTATION_TERM_NONE&&ContentOverlay.setRotationEvent(k,function(){getJsonP(c,b,getRequestURI(c,b,d))})}else AdEmbedded.createAd(c,b,a,d,m,{nolicense:h})}}};
function getParams(a){a=a.split("_");2>a.length&&(a[1]="");return{k:a[0],v:a[1]}}function getJsonP(a,c,b){b&&(a=AdCall.buildAdCallJsonP(b,Node.create),AdTagStatus.setSent(c),Node.appendHeadChild(a))}
function getRequestURI(a,c,b){var d=Dom.LOCATION_PROTOCOL+"//"+AMOAD_AD_DOMAIN+AMOAD_API_PATH,d=d+("sid="+a+"&url="+escape(document.URL)+"&ref="+escape(document.referrer));a=getAdTagParams(c);void 0!==a.rehearsal&&(d+="&rehearsal=1");(c=getAcSegs(b))&&(d+="&ac_segs="+encodeURIComponent(c));if(b.seg.ids&&!b.seg.segIdExist(c))return null;d=a.cb?d+("&cb="+a.cb):d+"&cb=adCallBack";void 0!==a.wv&&Dom.USERAGENT_IS_SMARTPHONE&&(d+="&wv=1");b.idfa.id?d+="&uid="+b.idfa.id+"&id_type=idfa&w=1":Dom.USERAGENT_IS_IOS_WEBVIEW&&
(d+="&w=1");b.request.toAdSpot&&(d+="&request_to_ad_spot=1");b.analytics.reportId&&(d=d+"&rparam="+encodeURIComponent(encodeURIComponent(b.analytics.reportId)));d=d+"&plog="+encodeURIComponent("com_amoad_sw:"+Window.top.screen.width+"|com_amoad_sh:"+Window.top.screen.height);Dom.LOCATION_IS_SSL&&(d+="&ssl=1");b.link.url&&(d+="&link="+encodeURIComponent(b.link.url));d+="&rnd="+Math.floor(1E3*Math.random());b.test.mode&&(d+="&test_mode="+b.test.mode);return d+="&version="+AMOAD_JS_VERSION}
function getAdTagParams(a){var c={};a=a.className.split(" ");for(var b=1;b<a.length;b++){var d=getParams(a[b]);c[d.k]="color"==d.k?d.v.split("-"):d.v}return c}function rightSegmentCall(){RightSegment.shouldCall()&&setTimeout(function(){RightSegment.reconfirmCall()&&RightSegment.dmpCall()},500)}function foxCall(){Fox.shouldCall()&&setTimeout(function(){Fox.reconfirmCall()&&Fox.dmpCall()},500)}function denaCall(){DeNA.shouldCall()&&setTimeout(function(){DeNA.reconfirmCall()&&DeNA.dmpCall()},500)}
function getAcSegs(a){var c=[];if(window.crtg_content&&!a.rta.isNone){var b=Criteo.segsOfContent(window.crtg_content);b&&c.push(b)}a.dmp.isNone||(Fox.shouldRequest()&&(b=Fox.getRequestCookie())&&c.push(b),DeNA.shouldRequest()&&(b=DeNA.getRequestCookie())&&c.push(b),RightSegment.shouldRequest()&&(b=RightSegment.getRequestCookie())&&c.push(b));(b=AdCall.modelSegs())&&c.push(b);return c.join("|")}Node.setGlobal("__adCallBack",callBack);
var DomContentLoaded=function(){return window.opera?function(){}:function(){for(var a=AdTag.amoadFrames(document),c=0;c<a.length;c++){var b=a[c].className.split(/\s+/);if(!(null==b||2>b.length||-1==b[1].indexOf("sid_")||AdTagStatus.isScanned(a[c]))&&(AdTagStatus.setScanned(a[c]),b=b[1].split("_")[1],64<=b.length)){var d=new AdTagOption(a[c]);getJsonP(b,a[c],getRequestURI(b,a[c],d))}}}}();
if(window.AS_manual_load){var startLoading=function(){DomContentLoaded()};window.AS_adLoad=function(){startLoading()};window.AS_manual_started&&window.AS_adLoad()}else startLoading=function(){Dom.USERAGENT_IS_SMARTPHONE&&(DomContentLoaded(),setTimeout(function(){DomContentLoaded();setTimeout(function(){DomContentLoaded();setTimeout(function(){DomContentLoaded();setTimeout(function(){DomContentLoaded()},2E3)},2E3)},1500)},500))},startLoading();})();
