(function(){var Style=function(){return{setProperty:function(a,c,b,d){d?a.setProperty(c,b,"important"):a.setProperty(c,b);return a}}}();String.prototype.startsWith||Object.defineProperty(String.prototype,"startsWith",{enumerable:!1,configurable:!1,writable:!1,value:function(a,c){c=c||0;return this.lastIndexOf(a,c)===c}});
String.prototype.endsWith||Object.defineProperty(String.prototype,"endsWith",{value:function(a,c){var b=this.toString();if(void 0===c||c>b.length)c=b.length;c-=a.length;b=b.indexOf(a,c);return-1!==b&&b===c}});
var Css3=function(){return{tapHighlightColor:function(a,c,b){Style.setProperty(a,"-webkit-tap-highlight-color",c,b)},transitionProperty:function(a,c,b){Style.setProperty(a,"transition-property",c,b);Style.setProperty(a,"-webkit-transition-property",c,b);Style.setProperty(a,"-moz-transition-property",c,b);Style.setProperty(a,"-ms-transition-property",c,b);Style.setProperty(a,"-o-transition-property",c,b)},transitionDuration:function(a,c,b){Style.setProperty(a,"transition-duration",c,b);Style.setProperty(a,
"-webkit-transition-duration",c,b);Style.setProperty(a,"-moz-transition-duration",c,b);Style.setProperty(a,"-ms-transition-duration",c,b);Style.setProperty(a,"-o-transition-duration",c,b)},transitionTimingFunction:function(a,c,b){Style.setProperty(a,"transition-timing-function",c,b);Style.setProperty(a,"-webkit-transition-timing-function",c,b);Style.setProperty(a,"-moz-transition-timing-function",c,b);Style.setProperty(a,"-ms-transition-timing-function",c,b);Style.setProperty(a,"-o-transition-timing-function",
c,b)},transformOrigin:function(a,c,b){Style.setProperty(a,"transform-origin",c,b);Style.setProperty(a,"-webkit-transform-origin",c,b);Style.setProperty(a,"-moz-transform-origin",c,b);Style.setProperty(a,"-ms-transform-origin",c,b);Style.setProperty(a,"-o-transform-origin",c,b)},transform:function(a,c,b){Style.setProperty(a,"transform",c,b);Style.setProperty(a,"-webkit-transform",c,b);Style.setProperty(a,"-moz-transform",c,b);Style.setProperty(a,"-ms-transform",c,b);Style.setProperty(a,"-o-transform",
c,b)},backgroundLinearGradient:function(a,c,b,d){Style.setProperty(a,"background","-webkit-gradient(linear, left top, left bottom, from("+c+"), to("+b+"))",d);Style.setProperty(a,"background","-moz-linear-gradient(top, "+c+", "+b+")",d)}}}(),AMOAD_AD_DOMAIN="n.amoad.com",AMOAD_CLICK_DOMAIN="d.amoad.com",AMOAD_JS_DOMAIN="j.amoad.com",AMOAD_JS_VERSION="3.2.0",AMOAD_API_DOMAIN="api1.amoad.com",AMOAD_API_PATH="/ad/jsonp/?",Utils=function(){var a=function(a,c){return b(a,new RegExp("(?:^|;[ ]*)"+c+"=([^;]*)"))},
c=function(a,c){return b(a,new RegExp("(?:^|[?&])"+c+"=([^&]*)"))},b=function(a,b){if(!a||!b)return"";var c=b.exec(a);return c&&2<=c.length&&c[1]?c[1]:""},d={getDomain:function(a){return(a=a.match(/^(.*?:\/\/)(.*?)([a-z0-9][a-z0-9\-]{1,63}\.[a-z\.]{2,6})[\:[0-9]*]?([\/].*?)?$/i))&&3<=a.length?a[3]:""},getNowDate:function(){return new Date},setCookieValue:function(a,b,c,d,m,l){a&&void 0!==a.cookie&&b&&(b=encodeURIComponent(b)+"=",c&&(b+=encodeURIComponent(c)),d&&(b+="; max-age="+d),m&&(b+="; domain="+
m),l&&(b+="; path="+l),a.cookie=b)},culcRandom:function(){return Math.floor(99999999999*Math.random())}};d.getCookie=a;d.getCookieValue=function(b,c){return decodeURIComponent(a(b,c))};d.getCsKeyValue=function(a,c){return b(a,new RegExp("(?:^|,[ ]*)"+c+"=([^,]*)"))};d.getJsQuery=c;d.getJsQueryValue=function(a,b){return decodeURIComponent(c(a,b))};d.getKeyValue=b;return d}(),Uuid=function(){var a={3:/^[0-9A-F]{8}-[0-9A-F]{4}-3[0-9A-F]{3}-[0-9A-F]{4}-[0-9A-F]{12}$/i,4:/^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/i,
5:/^[0-9A-F]{8}-[0-9A-F]{4}-5[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/i,all:/^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$/i};return{isUUID:function(c,b){var d=a[b?b:"all"];return d&&d.test(c)}}}(),Dom=function(){var a="https:"===document.location.protocol?!0:!1,c=a?"https:":"http:",b=window.location.hostname,d=window.location.href,e=b.match(/.*ameblo\.jp$/)||b.match(/.*ameba\.jp$/)||b.match(/.*candy\.am$/)?!0:!1,f=b.match(/.*mbga\.jp$/)?!0:!1,g="http://"+AMOAD_CLICK_DOMAIN+"/click/?cid=",
n=/iPhone/.test(navigator.userAgent)?!0:!1,m=/iPad/.test(navigator.userAgent)?!0:!1,l=n||m?!0:!1,h=/Android/.test(navigator.userAgent)?!0:!1,x=l||h?!0:!1,y=document,p=l&&!/Safari/.test(navigator.userAgent)?!0:!1,s;/iP(hone|od|ad)/.test(navigator.platform)?(s=navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/),s=[parseInt(s[1],10),parseInt(s[2],10),parseInt(s[3]||0,10)]):s=null;var r=n&&320<screen.width&&375>=screen.width?!0:!1,u=n&&375<screen.width?!0:!1,k={};k.LOCATION_IS_SSL=a;k.LOCATION_PROTOCOL=
c;k.LOCATION_HOSTNAME=b;k.LOCATION_HOSTNAME_IS_AMEBA=e;k.LOCATION_HOSTNAME_IS_MOBAGE=f;k.LOCATION_HREF=d;k.CLICK_URL_HEAD=g;k.USERAGENT_IS_IPHONE=n;k.USERAGENT_IS_IPAD=m;k.USERAGENT_IS_IOS=l;k.USERAGENT_IS_ANDROID=h;k.USERAGENT_IS_SMARTPHONE=x;k.DEVICE_IS_IPHONE_6=r;k.DEVICE_IS_IPHONE_6_PLUS=u;k.DOCUMENT=y;k.USERAGENT_IS_IOS_WEBVIEW=p;k.IOS_VERS=s;return k}(),Node=function(){var a=function(a){return document.createElement(a)},c=function(a){return document.getElementById(a)},b=function(a){for(var b=
a.childNodes.length-1;0<=b;b--)a.removeChild(a.childNodes[b])},d=function(a,b){a.setAttribute(b,"");a.removeAttribute(b)},e=function(a){return!a||0>=a.length?[]:Array.prototype.slice.call(a)},f={};f.create=a;f.resetStyle=function(a){a.style.margin="0";a.style.padding="0";a.style.border="none";return a};f.getHead=function(){return document.getElementsByTagName("head")[0]};f.buildScript=function(b,c,d){var f=a("script");d&&(f.id=d);f.src=b;f.type="text/javascript";f.async=c?!0:!1;return f};f.buildImgTag=
function(b,c){var d=a("img");c&&(d.id=c);d.src=b;d.width=1;d.height=1;return d};f.appendChild=function(a,b){a.appendChild(b)};f.appendHeadChild=function(a){Node.appendChild(Node.getHead(),a)};f.existForId=function(a){return document.getElementById(a)?!0:!1};f.getById=c;f.setGlobal=function(a,b){window[a]=b};f.getGlobal=function(a){return window[a]};f.clearChildren=b;f.createOrReplaceById=function(g,f){var m=c(g);m?(b(m),d(m,"style")):(m=a(f),m.id=g);return m};f.listToArray=e;f.nodesByClassName=function(a,
b){return e(a.getElementsByClassName(b))};f.nodesByTagName=function(a,b){return e(a.getElementsByTagName(b))};f.nodesFilterAttr=function(a,b,c){return a.filter(function(a){return a.getAttribute(b)===c},this)};f.appendSidNodeChild=function(a,b){"SCRIPT"===a.tagName?a.parentNode.insertBefore(b,a):a.appendChild(b)};f.removeAttribute=d;return f}(),Cookie=function(){return{getValue:function(a){return Utils.getCookieValue(document.cookie,a)},setValue:function(a,c,b,d,e){void 0===d&&(d=(d=Utils.getDomain(document.location.href))?
d:document.location.hostname);void 0===e&&(e="/");Utils.setCookieValue(document,a,c,b,d,e)}}}(),Impression=function(){var a=function(a){a&&((new Image(1,1)).src=a)},c={DELAY_MIN:500,DELAY_MAX:4E3,DELAY_DEFAULT:1E3,asyncSend:function(b,c){b&&0<c&&setTimeout(function(){a(b)},c)}};c.syncSend=a;c.delayMillis=function(a){return a&&a.impDelayMillis?Math.min(Math.max(a.impDelayMillis,500),4E3):1E3};c.bannerUrl=function(a){if(a){if(a.imp)return a.imp;if(a.ads&&a.ads[0].imp)return a.ads[0].imp}return null};
c.nativeUrl=function(a){return a&&a.NATIVE_IMP_URL?a.NATIVE_IMP_URL:null};return c}(),Window=function(){try{var a=window.top.location.protocol===window.location.protocol&&window.top.location.hostname===window.location.hostname&&window.top.location.port===window.location.port?window.top:window}catch(c){a=window}var b={};b.top=a;return b}(),AdTag=function(){var a=function(a){return Node.nodesByClassName(a,"amoad_native").concat(Node.nodesByClassName(a,"amoad_frame"))},c=function(a,b){return a?a.hasAttribute(b):
!1},b=function(a,b){return a?a.getAttribute(b):null},d=function(a,b,c){return a?a.setAttribute(b,c):null},e=function(a){return c(a,"data-sid")},f=function(a){return b(a,"data-sid")},g=function(a,b,c){return a?a.getAttribute(b)===c?!0:!1:!1},n={DATA_SID:"data-sid"};n.amoadFrames=a;n.sidNodes=function(b,c){return a(b).filter(function(a){return e(a)&&f(a)===c||-1!==a.className.indexOf("sid_"+c)})};n.hasAttr=c;n.getValue=b;n.setValue=d;n.getIntValue=function(a,c){return parseInt(b(a,c),10)};n.getPercentValue=
function(a,c){var d=b(a,c);return d&&-1!==d.indexOf("%")?parseInt(d,10)/100:-1};n.hasSid=e;n.getSid=f;n.setSid=function(a,b){return d(a,"data-sid",b)};n.firstChildValue=function(c,d){if(!c)return null;for(var g=null,f=a(c),e=0;e<f.length&&!(g=b(f[e],d));e++);return g};n.isValue=g;n.everyChildIsValue=function(b,c,d){if(!b)return!1;b=a(b);return 0>=b.length?!1:b.every(function(a){return g(a,c,d)})};n.valuesExist=function(a,b,c){if(!a)return null;a=a.split(c);var d=b.split(c);return a.some(function(a){return d.some(function(b){return a===
b})})};n.valueAsFunction=function(a){if(!a)return null;a=a.split(".");var b=Node.getGlobal(a[0]);if(!b)return null;for(var c=1,d=a.length;c<d;c++)if(b=b[a[c]],!b)return null;return"function"===typeof b?b:null};return n}(),AdTagStatus=function(){var a={none:0,scanned:1,sent:2,received:3,done:4},c=function(a){return a?(a=a.getAttribute("data-amoad-status"))?a:"":""},b=function(a,b){a&&b&&a.setAttribute("data-amoad-status",b)},d=function(b){return b?a[b]:0},e=function(a){if(!a||0>=a.length)return[];
if(1===a.length)return a;a=a.slice(0);a.sort(function(a,b){return d(c(a))-d(c(b))});return a},f=function(a,b){if(!a||0>=a.length)return null;var f=null;a.some(function(a){return d(c(a))>=b?(f=a,!0):!1});return f};return{isScanned:function(a){return 1<=d(c(a))},isSent:function(a){return 2<=d(c(a))},isReceived:function(a){return 3<=d(c(a))},isDone:function(a){return 4<=d(c(a))},setScanned:function(a){b(a,"scanned")},setSent:function(a){b(a,"sent")},setReceived:function(a){b(a,"received")},setDone:function(a){b(a,
"done")},findNone:function(a,b){var f=null;a.some(function(a){return 0==d(c(a))?(f=a,!0):!1});return f},findScannedBySid:function(a,b){return f(e(AdTag.sidNodes(a,b)),1)},findSentBySid:function(a,b){return f(e(AdTag.sidNodes(a,b)),2)},findReceivedBySid:function(a,b){return f(e(AdTag.sidNodes(a,b)),3)},findDoneBySid:function(a,b){return f(e(AdTag.sidNodes(a,b)),4)}}}(),AdTagRta=function(a){this.isNone=AdTag.isValue(a,"data-rta","none")};
AdTagRta.everyChildIsNone=function(a){return AdTag.everyChildIsValue(a,"data-rta","none")};var AdTagSeg=function(a){this.ids=AdTag.getValue(a,"data-seg-id");this.callback=AdTag.getValue(a,"data-seg-callback")};AdTagSeg.prototype.segIdExist=function(a){return AdTag.valuesExist(this.ids,a,"|")};AdTagSeg.prototype.asyncCallback=function(){var a=AdTag.valueAsFunction(this.callback);a&&setTimeout(function(){a.call(this)},300)};
var AdTagDmp=function(a){this.isNone=AdTag.isValue(a,"data-dmp","none")},AdTagStyle=function(a){this.width=AdTag.getValue(a,"data-style-width");this.height=AdTag.getValue(a,"data-style-height");this.float_=AdTag.getValue(a,"data-style-float");var c=AdTag.getPercentValue(a,"data-style-scale");this.scale=0.8<=c&&1>c||0.7===c?c:null;this.important=AdTag.hasAttr(a,"data-style-important");this.responsive=Dom.USERAGENT_IS_IPAD?!1:AdTag.hasAttr(a,"data-style-responsive");this.overlay={};this.overlay.clickRotation=
AdTag.hasAttr(a,"data-style-overlay-click-rotation");this.overlay.rigid=AdTag.hasAttr(a,"data-style-overlay-rigid");this.overlay.ease=AdTag.hasAttr(a,"data-style-overlay-ease");this.overlay.pr=Dom.USERAGENT_IS_IOS?AdTag.hasAttr(a,"data-style-overlay-pr"):!1};AdTagStyle.OVERLAY_CLICK_ROTATION_FLG_NAME="__com_amoad_overlay_click_rotation";
var AdTagIdfa=function(a){a=AdTag.getValue(a,"data-idfa");this.id=Uuid.isUUID(a)?a:null},AdTagRequest=function(a){this.toAdSpot=AdTag.hasAttr(a,"data-request-to-ad-spot")},AdTagTest=function(a){this.mode=Number(AdTag.firstChildValue(Dom.DOCUMENT,"data-test-mode"));switch(this.mode){case 1:Dom.USERAGENT_IS_SMARTPHONE=!0;Dom.USERAGENT_IS_IOS=!0;Dom.USERAGENT_IS_ANDROID=!1;break;case 2:Dom.USERAGENT_IS_SMARTPHONE=!0,Dom.USERAGENT_IS_IOS=!1,Dom.USERAGENT_IS_ANDROID=!0}},AdTagTemplate=function(){var a=
"NATIVE_UNIT_NO NATIVE_ADV_ID NATIVE_ICON_URL NATIVE_IMAGE_URL NATIVE_TITLE_SHORT NATIVE_TITLE_LONG NATIVE_SERVICE_NAME NATIVE_LINK NATIVE_LINK_BUTTON_URL NATIVE_LINK_ON_TAP_BUTTON_URL NATIVE_SPONSORED_LINK".split(" "),c=function(a){return Node.nodesByClassName(a,"amoad_template")},b=function(a,b){return a.some(function(a){return AdTag.hasSid(a)&&AdTag.getSid(a)===b?!0:!1})},d=function(a){if(a=a.sponsoredHtml)return'<a href="http://d.amoad.com/guideline/" target="_blank" style="text-decoration: none; -webkit-tap-highlight-color: rgba(0,0,0,0);">'+
a+"</a>"};window.__amoadNativeTemplate=function(a){var d=a.sid;if(!b(c(document,d),d)){a=a.html;var e=Node.create("script");e.type="text/amoad-template";e.className="amoad_template";AdTag.setSid(e,d);e.innerHTML=a;Node.appendHeadChild(e)}};var e={};e.templateNodes=c;e.exists=b;e.value=function(a,b){var c="";a.some(function(a){return AdTag.hasSid(a)&&AdTag.getSid(a)===b?(c=a.innerHTML,!0):!1});return c};e.extractMacro=function(b,c,e){if(!b||!c)return"";e&&((e=d(e))&&(c.NATIVE_SPONSORED_LINK=e),(e=
c.advId)&&(c.NATIVE_ADV_ID=e));var m=b;a.forEach(function(a){m=m.replace(new RegExp("\\${"+a+"}","g"),void 0!==c[a]&&null!==c[a]?c[a]:"")});return m};e.removeCommentOut=function(a){var b=a.trim();return b.startsWith("/*")&&b.endsWith("*/")?b.substring(2,b.length-2).trim():a};return e}(),AdTagClick=function(a){this.params=AdTag.getValue(a,"data-click-params")},AdTagAnalytics=function(a){this.reportId=AdTag.getValue(a,"data-analytics-report-id")},AdTagLink=function(a){this.url=AdTag.getValue(a,"data-link")},
AdTagOption=function(a){this.analytics=new AdTagAnalytics(a);this.click=new AdTagClick(a);this.dmp=new AdTagDmp(a);this.rta=new AdTagRta(a);this.idfa=new AdTagIdfa(a);this.request=new AdTagRequest(a);this.seg=new AdTagSeg(a);this.style=new AdTagStyle(a);this.link=new AdTagLink(a);this.test=new AdTagTest(a)},DmpSegs=function(){return{dmpToAmSegsStr:function(a,c,b,d,e){return a.sort(function(a,c){var d;if(d=a[b]){var e=c[b];d=e?e-d:-1}else d=1;return d}).map(function(a){a=(a=a[c])?d[a]:null;return a}).filter(function(a){return a?
!0:!1}).slice(0,e).join("|")}}}(),Fox=function(){var a=function(a){Cookie.setValue("amoad_fox_called2","true",86400);a&&Object.keys(a).length&&a.segs&&"number"===typeof a.segs.length&&0<a.segs.length&&(Node.setGlobal("__amoadFoxJsonCallBack",function(b){Cookie.setValue("amoad_fox_request_segs",DmpSegs.dmpToAmSegsStr(a.segs,"seg_id","ts",b,300),2592E3)}),Node.appendHeadChild(Node.buildScript("http://j.amoad.com/js/fox.json",!0,"amoad_fox_json")))},c=function(){return Node.existForId("amoad_fox_loader")||
Cookie.getValue("amoad_fox_called2")?!1:!0},b={dmpCall:function(){Node.setGlobal("__amoadFoxCallBack",a);Node.appendHeadChild(Node.buildScript("http://dmp.app-adforce.jp/ad/i/rta?_pcd=aa&_method=window%2e__amoadFoxCallBack",!0,"amoad_fox_loader"))}};b.reconfirmCall=c;b.shouldCall=function(){return!Dom.LOCATION_IS_SSL&&c()?!0:!1};b.shouldRequest=function(){return!0};b.getRequestCookie=function(){return Cookie.getValue("amoad_fox_request_segs")};return b}(),DeNA=function(){var a=function(a){Cookie.setValue("amoad_dena_called2",
"true",86400);a&&Object.keys(a).length&&a.segs&&"number"===typeof a.segs.length&&0<a.segs.length&&(Node.setGlobal("__amoadDeNAJsonCallBack",function(b){Cookie.setValue("amoad_dena_request_segs",DmpSegs.dmpToAmSegsStr(a.segs,"seg_id","ts",b,300),2592E3)}),Node.appendHeadChild(Node.buildScript("http://j.amoad.com/js/dena.json",!0,"amoad_dena_json")),Dynalyst.denaSend(a.segs))},c=function(){return Node.existForId("amoad_dena_loader")||Cookie.getValue("amoad_dena_called2")?!1:!0},b={dmpCall:function(){Node.setGlobal("__amoadDeNACallBack",
a);Node.appendHeadChild(Node.buildScript("http://ad_rta.sp.mbga.jp/_api_amoad_segment?cb=__amoadDeNACallBack",!0,"amoad_dena_loader"))}};b.reconfirmCall=c;b.shouldCall=function(){return!Dom.LOCATION_IS_SSL&&c()?!0:!1};b.shouldRequest=function(){return!0};b.getRequestCookie=function(){return Cookie.getValue("amoad_dena_request_segs")};return b}(),Dynalyst=function(){var a=encodeURIComponent("FINAL FANTASY Record Keeper(RTA)"),c=["44","36","7","4"],b="",d=!0;Dom.USERAGENT_IS_IOS?b="_IOS":Dom.USERAGENT_IS_ANDROID?
b="_ANDROID":d=!1;var e=function(b,c,d,e){b=b+"?an="+a+"&advid=1256&cty=JPN&tz=JST&dtype="+d+"&uq="+e+"&restype=gif&ext="+encodeURIComponent('{"category":"'+c+'"}');(new Image(1,1)).src=b},f={denaSend:function(a){if(d)for(var f=0;f<c.length;f++)for(var m=c[f],l=0;l<a.length;l++){var h=a[l].seg_id;if(h==m){h+=b;Cookie.getValue("amoad_dynalyst_request_seg")!=h&&(a=Utils.culcRandom(),e("http://dynalyst-mk.adtdp.com/site/game/ext",h,"1",a),e("http://mk.ca-conv.amoad.com/site/game/ext",h,"2",a));Cookie.setValue("amoad_dynalyst_request_seg",
h,2592E3);return}}}};f.beaconSend=e;return f}(),RightSegment=function(){var a=function(a){Cookie.setValue("amoad_rs_called2","true",86400);a&&Object.keys(a).length&&a.segments&&"number"===typeof a.segments.length&&0<a.segments.length&&(Node.setGlobal("__amoadRsJsonCallBack",function(b){Cookie.setValue("amoad_rs_request_segs",DmpSegs.dmpToAmSegsStr(a.segments,"seg_key","epoch",b,300),2592E3)}),Node.appendHeadChild(Node.buildScript("http://j.amoad.com/js/rs.json",!0,"amoad_rs_json")))},c=function(){return Node.existForId("amoad_rs_loader")||
Cookie.getValue("amoad_rs_called2")?!1:!0},b={dmpCall:function(){Node.setGlobal("__amoadRsCallBack",a);Node.appendHeadChild(Node.buildScript("http://rs-ap.adtdp.com/rta/?pid=bac2ea9ceb76beba&callback=__amoadRsCallBack",!0,"amoad_rs_loader"))}};b.reconfirmCall=c;b.shouldCall=function(){return!Dom.LOCATION_IS_SSL&&c()?!0:!1};b.shouldRequest=function(){return!0};b.getRequestCookie=function(){return Cookie.getValue("amoad_rs_request_segs")};return b}(),Criteo=function(){var a=[["crta_amoad_(?:ios_)*300250.*;",
"Q0x.0.1H2"],["crta_amoad_(?:ios_)*32050.*;","Q0x.0.1GG"],["crta_aa_deco_300250.*;","Q0x.0.1J2"]],c=[["crta_aa_amb_(?:ios_)*32050.*;","Q0x.0.1Gz"],["crta_aa_amb_300100.*;","Q0x.0.1J1"]],b=[["crta_aa_mbg_(?:ios_)*32050.*;","Q0x.0.1H0"]];return{LOADER_ID:"amoad_criteo_rta",buildLoader:function(a,b,c){a=Dom.LOCATION_PROTOCOL+"//rtax.criteo.com/delivery/rta/rta.js?netId="+escape("2490")+"&cookieName="+escape("crtg_amoad_rta")+"&rnd="+a.call(this)+"&varName="+escape("crtg_content");b=b.call(this,"script");
b.type="text/javascript";b.id="amoad_criteo_rta";b.src=a;b.async=c;return b},segsOfContent:function(d){if(!d)return"";var e=[];Dom.LOCATION_HOSTNAME_IS_MOBAGE?b.map(function(a){(new RegExp(a[0])).test(d)&&e.push(a[1])}):Dom.LOCATION_HOSTNAME_IS_AMEBA?c.map(function(a){(new RegExp(a[0])).test(d)&&e.push(a[1])}):a.map(function(a){(new RegExp(a[0])).test(d)&&e.push(a[1])});return e.join("|")}}}(),DirectStore=function(a,c,b){this.appId=a;this.beacon=c;this.href=b?"itms-apps://itunes.apple.com/app/id"+
a:"market://details?id="+a};DirectStore.prototype.sendClick=function(){this.beacon&&((new Image(1,1)).src=this.beacon)};
var Scale=function(a){var c=function(a){if(a||Scale.window===Scale.window.top)if(Dom.USERAGENT_IS_ANDROID)if(a=Scale.window.innerWidth,a>Scale.window.innerHeight){var b=Math.max(Scale.screen.width,Scale.screen.height),c=Math.min(Scale.screen.width,Scale.screen.height);a=Math.max(b>=1.5*a?c*a/b:c,320)}else b=Math.min(Scale.screen.width,Scale.screen.height),Math.max(Scale.screen.width,Scale.screen.height),a=Math.max(b>=1.5*a?b*a/b:b,320);else{if(Dom.USERAGENT_IS_IPAD)return 400*Scale.window.innerWidth/
Scale.screen.width;a=Scale.screen.width}else a=0;return a?a:320},b=function(a){return c(a)/320},d={};d.window=a;d.screen=a.screen;d.BASE_WIDTH=320;d.BASE_WIDTH_OLD_ANDROID=320;d.windowWidth=c;d.responsiveScale=b;d.responsiveSize=function(a,c,d){d=b(d);return{width:a*d,height:c*d}};return d}(window),MultiAd=function(){function a(a){this.sid=a;this.arg=this.loader=null}var c=Window.top;return{getItem:function(b){var d=c["com_amoad_native_multiAd_"+b];d||(d=new a(b),c["com_amoad_native_multiAd_"+b]=
d);return d},removeItem:function(a){return delete c["com_amoad_native_multiAd_"+a]}}}(),Content=function(){var a=function(a,b){var c=a.style,d=b.style.important;Style.setProperty(c,"border","none",d);Style.setProperty(c,"margin","0",d);Style.setProperty(c,"padding","0",d);return c},c=function(a,b){a.addEventListener("touchstart",function(a){a.stopPropagation();b.style.overlay.clickRotation&&Node.setGlobal(AdTagStyle.OVERLAY_CLICK_ROTATION_FLG_NAME,!0)},!1);a.addEventListener("touchend",function(a){a.stopPropagation()},
!1);a.addEventListener("scroll",function(a){a.stopPropagation()},!1)},b=function(a,b){return a.useDirectStore?function(c,d){return e(a.appId,c,d,b)}:function(a,c){return d(a,c,b)}},d=function(a,b,c){var d=document.createElement("a");d.target="_blank";d.href=b.click.params?a+"&"+b.click.params:a;Style.setProperty(d.style,"text-decoration","none",c);Dom.USERAGENT_IS_IOS_WEBVIEW||(d.onclick=function(){window.open(this.href,this.target);return!1});return d},e=function(a,b,c,d){var e=new DirectStore(a,
b,Dom.USERAGENT_IS_IOS);a=document.createElement("a");a.target="_blank";a.href=c.click.params?e.href+"&"+c.click.params:e.href;Style.setProperty(a.style,"text-decoration","none",d);a.onclick=function(){e.sendClick();window.open(this.href,this.target);return!1};return a},f=function(b,c){var d=Node.create("img"),k=a(d,c);d.src=b;d.alt="";var e=c.style.important;Style.setProperty(k,"float","left",e);Style.setProperty(k,"margin-left","5px",e);Style.setProperty(k,"margin-top","6px",e);Style.setProperty(k,
"width","38px",e);Style.setProperty(k,"height","38px",e);return d},g=function(b,c,d){c=Node.create("div");var k=a(c,d);c.innerHTML=decodeURIComponent(b);d=d.style.important;Style.setProperty(k,"float","left",d);Style.setProperty(k,"margin-left","5px",d);Style.setProperty(k,"margin-top","6px",d);Style.setProperty(k,"width","250px",d);Style.setProperty(k,"height","38px",d);Style.setProperty(k,"font-weight","500",d);Style.setProperty(k,"text-align","left",d);Style.setProperty(k,"word-wrap","break-word",
d);Style.setProperty(k,"word-break","break-all",d);for(var e=0,f=0,h=b.length;f<h;f++)e=4>escape(b.charAt(f)).length?e+0.7:e+1;b=e;e=250;12*b>e&&(e*=2);b=Math.floor(e/b);b=Math.min(b,29);fontSize=b=Math.max(b,9);Style.setProperty(k,"color","color",d);Style.setProperty(k,"font-size",fontSize+"px",d);Style.setProperty(k,"line-height",fontSize+4+"px",d);return c},n=function(b,c){var d=Node.create("div"),k=a(d,c);d.innerHTML="ads by AMoAd";var e=c.style.important;Style.setProperty(k,"position","absolute",
e);Style.setProperty(k,"bottom","1px",e);Style.setProperty(k,"right","5px",e);Style.setProperty(k,"font-weight","400",e);Style.setProperty(k,"text-align","left",e);k.color=b;k.fontSize="9px";k.lineHeight="9px";return d},m=function(a,b){return a.useDirectStore?function(c,d){l(c,b,a.appId)}:function(a,c){h(a,b,c)}},l=function(a,b,c){Node.nodesByTagName(a,"a").filter(function(a){return a.href&&0===a.href.indexOf(b)}).map(function(a){var b=new DirectStore(c,a.href,Dom.USERAGENT_IS_IOS);a.href=b.href;
Node.removeAttribute(a,"onclick");a.onclick=function(){b.sendClick();window.open(b.href,"_blank");return!1}})},h=function(a,b,c){Node.nodesByTagName(a,"a").filter(function(a){return a.href&&0===a.href.indexOf(b)}).map(function(a){Node.removeAttribute(a,"onclick");a.href=c.click.params?a.href+"&"+c.click.params:a.href;Dom.USERAGENT_IS_IOS_WEBVIEW||(a.onclick=function(){window.open(a.href,"_blank");return!1})})},x=function(b,d,e,k){var f=Node.create("iframe");d=a(f,k);setTimeout(function(){var a=b.replace(/\+/g,
" ");f.contentDocument.writeln(decodeURIComponent(a));f.contentDocument.close();e(f.contentDocument,k)},0);var h=k.style.important;Style.setProperty(d,"position","relative",h);Style.setProperty(d,"display","block",h);Style.setProperty(d,"width","100%",h);Style.setProperty(d,"height","100%",h);c(f,k);return f},y=function(b,d,e,f){var h=Node.create("iframe");d=a(h,f);h.src=b;setTimeout(function(){e(h.contentDocument,f)},0);b=f.style.important;Style.setProperty(d,"position","relative",b);Style.setProperty(d,
"display","block",b);Style.setProperty(d,"width","100%",b);Style.setProperty(d,"height","100%",b);c(h,f);return h},p={create:function(d,e,h,k,p){var l=null,t="giftext"===d?e.ads[0]:e;switch(d){case "img":l=t.src;h=Node.create("img");k=a(h,p);h.src=l;h.alt="";l=p.style.important;Style.setProperty(k,"position","relative",l);Style.setProperty(k,"display","block",l);Style.setProperty(k,"width","100%",l);Style.setProperty(k,"height","100%",l);Style.setProperty(k,"box-shadow","rgb(0, 0, 0) 0 0 3px",l);
c(h,p);l=b(t)(t.href,p);l.appendChild(h);break;case "giftext":k=t.src;l=t.title;e=e.nolicense;d=parseInt(h[2].substring(1,3),16);var B=parseInt(h[2].substring(3,5),16),C=parseInt(h[2].substring(5,7),16),z=Node.create("div"),v=a(z,p),w=p.style.important;Style.setProperty(v,"position","relative",w);Style.setProperty(v,"display","block",w);Style.setProperty(v,"width","100%",w);Style.setProperty(v,"height","100%",w);Style.setProperty(v,"box-shadow","rgb(0, 0, 0) 0 0 3px",w);Style.setProperty(v,"border-top-left-radius",
"3px",w);Style.setProperty(v,"border-bottom-left-radius","3px",w);Style.setProperty(v,"border-bottom-right-radius","3px",w);Css3.backgroundLinearGradient(v,"rgb("+d+", "+B+", "+C+")","rgba("+d+", "+B+", "+C+", 0.9)",w);k&&Node.appendChild(z,f(k,p));l&&Node.appendChild(z,g(l,h[0],p));e||Node.appendChild(z,n(h[1],p));c(z,p);h=z;l=b(t)(t.href,p);l.appendChild(h);break;case "html":h=m(t,Dom.CLICK_URL_HEAD),l=t.html?x(t.html,k,h,p):y(t.iframeLocation,k,h,p)}return l},prAnchorCreate:function(b,e){var f=
Node.create("div"),h=a(f,e);Style.setProperty(h,"height",ContentOverlay.PR_HEIGHT+"px",!1);Style.setProperty(h,"text-align","center",!1);Style.setProperty(h,"background-color","#000",!1);Style.setProperty(h,"color","#fff",!1);Style.setProperty(h,"line-height",ContentOverlay.PR_HEIGHT+"px",!1);Style.setProperty(h,"font-size","12px",!1);Style.setProperty(h,"width","100%",!1);Style.setProperty(h,"position","relative",!1);Style.setProperty(h,"text-decoration","none",!1);Css3.tapHighlightColor(h,"rgba(0,0,0,0)",
!1);c(f,e);h=new Image;h.src="http://stg-i.amoad.net/creatives/shared/pr.png";var g=h.style;Style.setProperty(g,"position","relative",!0);Style.setProperty(g,"margin","5px 0",!0);Style.setProperty(g,"height","16px",!0);f.appendChild(h);return b?(h=d(b,e),h.appendChild(f),h):f}};p.anchorCreatorForAd=b;p.htmlConverterForAd=m;return p}(),ContentOverlay=function(){var a=function(a,b){a.display=b?"block":"none"},c=function(b,c,e,f,g,l,m,k){document.addEventListener("touchstart",function(){a(b,!1);e&&Node.getGlobal(AdTagStyle.OVERLAY_CLICK_ROTATION_FLG_NAME)&&
(Node.setGlobal(AdTagStyle.OVERLAY_CLICK_ROTATION_FLG_NAME,!1),e.call(this))},!1);document.addEventListener("touchend",function(){c?(a(b,!0),d(b,c,f,g,l,m,k)):setTimeout(function(){a(b,!0);d(b,c,f,g,l,m,k)},1E3)},!1);if(Dom.USERAGENT_IS_ANDROID){var n;document.addEventListener("scroll",function(){n&&clearTimeout(n);a(b,!1);n=setTimeout(function(){n=null;a(b,!0);d(b,c,f,g,l,m,k)},1E3)},!1)}},b=function(a,b,c,d,g,l){document.addEventListener("scroll",function(){var m=e(b);(a.top?"top":"bottom")!==m&&
(g&&(a.height="bottom"===m?l+28/c+"px":l+"px"),f(a,d,c,m,!0))},!1)},d=function(a,b,c,d,g,m,l){c=g?c:e(c);(g=(a.top?"top":"bottom")!==c)&&m&&(a.height="bottom"===c?l+28/d+"px":l+"px");f(a,b,d,c,g)},e=function(a){return"bottom"===a?window.pageYOffset+window.innerHeight>Math.max(document.documentElement.scrollHeight,document.body.scrollHeight)-100?"top":"bottom":100>window.pageYOffset?"bottom":"top"},f=function(a,b,c,d,e){c&&e&&(Css3.transitionDuration(a,"0ms"),Css3.transformOrigin(a,"center "+d),Css3.transform(a,
"scale("+c+")"));b?g(a,d):n(a,d,e?20:0)},g=function(a,b){Css3.transitionDuration(a,"0ms");a.opacity="0";m(a,b,0);setTimeout(function(){Css3.transitionDuration(a,"3500ms");a.opacity="1"},0)},n=function(a,b,c){Css3.transitionDuration(a,"0ms");a.opacity="0";m(a,b,c);setTimeout(function(){Css3.transitionDuration(a,"300ms");m(a,b,0);a.opacity="1"},0)},m=function(a,b,c){c||(c=0);a.removeProperty("top");a.removeProperty("bottom");a[b]=c+"px"},l={POS_BOTTOM:"bottom",POS_TOP:"top",PR_HEIGHT:28,overlay:function(a,
b,c){var d=a.style;d.position="relative";d.overflow="hidden";d.width=b+"px";d.height=c+"px";d.margin="0 auto";d.padding="0";return a},overlaySpace:function(d,e,f,g,l,m,n,k,A){var q=d.style;q.position="fixed";q.left="0";q.right="0";q.width="100%";q.overflow="hidden";q.margin="0";q.padding="0";q.transitionProperty="all";Css3.tapHighlightColor(q,"rgba(0,0,0,0)",!0);q.zIndex="800";a(q,!1);l?m||b(q,g,f,n,k,e):c(q,n,A,g,f,m,k,e);return d}};l.setStyleDisplay=a;l.startAnimation=function(a,b,c,d,g,m,l){b=
d?b:e(b);a.height=m&&"bottom"===b?l+28/c+"px":l+"px";f(a,g,c,b,!0)};l.setRotationEvent=function(a,b){var c=function(){document.removeEventListener("touchstart",c,!1);setTimeout(function(){b.call(this)},1E3*a)};document.addEventListener("touchstart",c,!1)};return l}(),ContentDiv=function(){return{setStyle:function(a,c,b,d){Style.setProperty(a,"visibility","hidden",d);Style.setProperty(a,"position","relative",d);Style.setProperty(a,"overflow","hidden",d);Style.setProperty(a,"width",c,d);Style.setProperty(a,
"height",b,d);Style.setProperty(a,"margin","0 auto",d);Css3.tapHighlightColor(a,"rgba(0,0,0,0)",d)},show:function(a,c){Style.setProperty(a,"visibility","visible",c)}}}(),LICENSE_TEXT_SIZE=10,LICENSE_STRING="ads by AMoAd",BLOCK_MARGIN=5,TOP_BLOCK_MARGIN=5,AMoAdSmartphone={htmlNode:function(a,c,b,d,e,f,g,n){var m=document.createElement("iframe");a=m.style;c=g.style.important;Style.setProperty(a,"position","relative",c);Style.setProperty(a,"border","none",c);g.style.width?Style.setProperty(a,"width",
g.style.width,c):Style.setProperty(a,"width",b+"px",c);g.style.height?Style.setProperty(a,"height",g.style.height,c):Style.setProperty(a,"height",d+"px",c);g.style.float_&&Style.setProperty(a,"float",g.style.float_,c);Style.setProperty(a,"margin","0pt auto",c);Style.setProperty(a,"display","block",c);g.style.scale?(b=g.style.scale,Css3.transformOrigin(a,"left top",c),Css3.transform(a,"scale("+b+")",c)):g.style.responsive&&(b=Scale.responsiveScale(),Css3.transformOrigin(a,"center top",c),Css3.transform(a,
"scale("+b+")",c));if(e){var l=decodeURIComponent(e.replace(/\+/g," "));setTimeout(function(){m.contentDocument.writeln(l);m.contentDocument.close();n(m.contentDocument,g)},0)}else m.src=f,setTimeout(function(){n(m.contentDocument,g)},0);return m}};
function SmartphoneEmbedded(){function a(a,c,e,f,g){var n=[],m=e.style.important;if("object"==typeof g)for(var l in g)if("size"==l||"size_overturn"==l)g[l].match(/px|%$/i)||(g[l]+="px");var h=function(e,g){var l=AdTagStatus.findReceivedBySid(document,a);if(l){l.children&&0!=l.childNodes.length||(n=[],c=l);var h=e.height?e.height:e.ads.height,r=e.width?e.width:e.ads.width,l=e.type,u=document.createElement("div");if(g.style.scale){for(var k=c.parentNode,A=null;k&&k!==document.body.parentNode&&null!==
(A=getComputedStyle(k));){var q=A.zoom;if(1<q||1>q){Style.setProperty(c.style,"zoom",1/q,m);break}k=k.parentNode}k=g.style.scale;r=r*k+"px";h=h*k+"px"}else g.style.responsive?(k=Scale.responsiveScale(!0),h=Scale.responsiveSize(r,h),r=h.width+"px",h=h.height+"px"):(k=1,r=g.style.width?g.style.width:r+"px",h=g.style.height?g.style.height:h+"px");ContentDiv.setStyle(u.style,r,h,m);n.push(u);h=Content.create(l,e,f,k,g);u.appendChild(h);"html"!==l&&InfoMarker.images(Node.create("div"),Node.create("div"),
Node.create("a"),!0).map(function(a){u.appendChild(a)});Node.appendSidNodeChild(c,u);Impression.asyncSend(Impression.bannerUrl(e),Impression.delayMillis(e));g.seg.callback&&g.seg.asyncCallback();g.dmp.isNone||(foxCall(),denaCall(),rightSegmentCall());AdTagStatus.setDone(c)}};this.createAd=function(a,b){h(a,b);1<n.length?(ContentDiv.show(n[n.length-1].style,m),c.removeChild(n.shift())):ContentDiv.show(n[n.length-1].style,m)}}var c=[];this.createAd=function(b,d,e,f,g,n){for(var m=!1,l,h=0,x=c.length;h<
x;h++)if(c[h].sid==b){l=c[h].obj;m=!0;break}!1==m&&(l=new a(b,d,f,g,n),c.push({sid:b,obj:l}));l.createAd(e,f)}}
var AdEmbedded=function(){var a=function(a,b,d,e,f){var g=Node.resetStyle(Node.create("div"));"nativeIframe"!==d.displayFormat&&(f.style.width&&Style.setProperty(g.style,"width",f.style.width),f.style.height&&Style.setProperty(g.style,"height",f.style.height),f.style.float_&&Style.setProperty(g.style,"float",f.style.float_));if("nativeIframe"===d.displayFormat){var n=Content.htmlConverterForAd(e,Dom.CLICK_URL_HEAD),m=AMoAdSmartphone.htmlNode(a,b,d.nativeIframe.width,d.nativeIframe.height,e.NATIVE_HTML,
null,f,n);g.appendChild(m)}else{var l=AdTagTemplate.templateNodes(document);AdTagTemplate.exists(l,a)?m=AdTagTemplate.removeCommentOut(AdTagTemplate.value(l,a)):d.NATIVE_TEMPLATE?m=decodeURIComponent(d.NATIVE_TEMPLATE.replace(/\+/g," ")):d.nativeWebTemplates&&d.nativeWebTemplates.adsContainer&&(m=decodeURIComponent(d.nativeWebTemplates.adsContainer.replace(/\+/g," ")));m&&(n=Content.htmlConverterForAd(e,e.NATIVE_LINK),e.useDirectStore&&(a=new DirectStore(e.appId,e.NATIVE_LINK,Dom.USERAGENT_IS_IOS),
e.NATIVE_LINK=a.href),f.click.params&&(e.NATIVE_LINK=e.NATIVE_LINK+"&"+f.click.params),g.innerHTML=AdTagTemplate.extractMacro(m,e,d),setTimeout(function(){n(g,f)},0))}Node.appendSidNodeChild(b,g);AdTagStatus.setDone(b);Impression.asyncSend(Impression.nativeUrl(e),Impression.delayMillis(d));f.seg.callback&&f.seg.asyncCallback()};return{createAd:function(c,b,d,e,f,g){(f=d.ads)&&0<f.length&&(a(c,b,d,f.shift(),e),0<f.length?MultiAd.getItem(c).arg=d:d.allowDuplicatedAds&&MultiAd.removeItem(c))}}}(),AdOverlay=
function(){return{createAd:function(a,c,b,d,e,f,g){a=b.type;var n=1;if("img"===a){var m=Scale.responsiveSize(b.width,b.height,!0);f=m.width;var l=m.height}else if(f=b.width,l=b.height,"html"===a||"giftext"===a)n=Scale.responsiveScale(!0);var h="HEADER"===b.position?ContentOverlay.POS_TOP:ContentOverlay.POS_BOTTOM,m=b.is_fixed,x=d.style.overlay.rigid,y=d.style.overlay.ease,p=h==ContentOverlay.POS_BOTTOM&&d.style.overlay.pr,s=Content.create(a,b,e,n,d);if(s){e=ContentOverlay.overlay(Node.create("div"),
f,l);e.appendChild(s);"html"!==a&&InfoMarker.images(Node.create("div"),Node.create("div"),Node.create("a"),!0).map(function(a){s.appendChild(a)});var r=ContentOverlay.overlaySpace(Node.createOrReplaceById("ad_cloud_overlay_space","div"),l,n,h,m,x,y,p,g);r.appendChild(e);if(p){switch(a){case "img":var u=b.href;break;case "giftext":u=b.ads[0].href}r.appendChild(Content.prAnchorCreate(u,d))}Node.appendSidNodeChild(c,r);AdTagStatus.setDone(c);setTimeout(function(){ContentOverlay.startAnimation(r.style,
h,n,x,y,p,l);ContentOverlay.setStyleDisplay(r.style,!0)},500);Impression.asyncSend(Impression.bannerUrl(b),Impression.delayMillis(b));d.dmp.isNone||(foxCall(),denaCall(),rightSegmentCall())}}}}(),AdCall=function(){return{buildAdCallJsonP:function(a,c,b){c=c.call(b,"script");c.type="text/javascript";c.charset="utf-8";c.src=a;c.async=!0;return c},modelSegs:function(){return Dom.DEVICE_IS_IPHONE_6?"Q0x.0.1Jz|Q0x.0.1K0":Dom.DEVICE_IS_IPHONE_6_PLUS?"Q0x.0.1Jz|Q0x.0.1K1":""}}}(),ROTATION_TERM_NONE=99999,
callBack=function(a,c){if(a.type){var b=AdTagStatus.findSentBySid(document,c);if(b){AdTagStatus.setReceived(b);var d=new AdTagOption(b),e=getAdTagParams(b),f=void 0!==e.nolicense,g=a.rotation?a.rotation:ROTATION_TERM_NONE,n=e.color?e.color:a.color?a.color.split("-"):"";if(!0==a.is_overlay){if(d.style.overlay.clickRotation)var m=function(){getJsonP(c,b,getRequestURI(c,b,d))};AdOverlay.createAd(c,b,a,d,n,{fixed:a.is_fixed?a.is_fixed:!1,nolicense:f,position:a.position?a.position:"FOOTER",size:a.height+
"px",size_overturn:a.height+"px",ad_base_color:n[2]},m);void 0!==e.rotationterm&&0<e.rotationterm&&(g=e.rotationterm);a.rotation_type&&a.bill_type&&"STOP_CPM"==a.rotation_type&&"CPM"==a.bill_type&&(g=ROTATION_TERM_NONE);g!==ROTATION_TERM_NONE&&ContentOverlay.setRotationEvent(g,function(){getJsonP(c,b,getRequestURI(c,b,d))})}else AdEmbedded.createAd(c,b,a,d,n,{nolicense:f})}}};function getParams(a){a=a.split("_");2>a.length&&(a[1]="");return{k:a[0],v:a[1]}}
function getJsonP(a,c,b){b&&(a=AdCall.buildAdCallJsonP(b,Node.create),AdTagStatus.setSent(c),Node.appendHeadChild(a))}
function getRequestURI(a,c,b){var d=Dom.LOCATION_PROTOCOL+"//"+AMOAD_AD_DOMAIN+AMOAD_API_PATH,d=d+("sid="+a+"&url="+escape(document.URL)+"&ref="+escape(document.referrer));a=getAdTagParams(c);void 0!==a.rehearsal&&(d+="&rehearsal=1");(c=getAcSegs(b))&&(d+="&ac_segs="+encodeURIComponent(c));if(b.seg.ids&&!b.seg.segIdExist(c))return null;d=a.cb?d+("&cb="+a.cb):d+"&cb=__amoadNativeCallback";void 0!==a.wv&&Dom.USERAGENT_IS_SMARTPHONE&&(d+="&wv=1");b.idfa.id?d+="&uid="+b.idfa.id+"&id_type=idfa&w=1":Dom.USERAGENT_IS_IOS_WEBVIEW&&
(d+="&w=1");b.request.toAdSpot&&(d+="&request_to_ad_spot=1");b.analytics.reportId&&(d=d+"&rparam="+encodeURIComponent(encodeURIComponent(b.analytics.reportId)));d=d+"&plog="+encodeURIComponent("com_amoad_sw:"+Window.top.screen.width+"|com_amoad_sh:"+Window.top.screen.height);Dom.LOCATION_IS_SSL&&(d+="&ssl=1");b.link.url&&(d+="&link="+encodeURIComponent(b.link.url));d+="&rnd="+Math.floor(1E3*Math.random());b.test.mode&&(d+="&test_mode="+b.test.mode);return d+="&version="+AMOAD_JS_VERSION}
function getAdTagParams(a){var c={};a=a.className.split(" ");for(var b=1;b<a.length;b++){var d=getParams(a[b]);c[d.k]="color"==d.k?d.v.split("-"):d.v}return c}function rightSegmentCall(){RightSegment.shouldCall()&&setTimeout(function(){RightSegment.reconfirmCall()&&RightSegment.dmpCall()},500)}function foxCall(){Fox.shouldCall()&&setTimeout(function(){Fox.reconfirmCall()&&Fox.dmpCall()},500)}function denaCall(){DeNA.shouldCall()&&setTimeout(function(){DeNA.reconfirmCall()&&DeNA.dmpCall()},500)}
function getAcSegs(a){var c=[];if(window.crtg_content&&!a.rta.isNone){var b=Criteo.segsOfContent(window.crtg_content);b&&c.push(b)}a.dmp.isNone||(Fox.shouldRequest()&&(b=Fox.getRequestCookie())&&c.push(b),DeNA.shouldRequest()&&(b=DeNA.getRequestCookie())&&c.push(b),RightSegment.shouldRequest()&&(b=RightSegment.getRequestCookie())&&c.push(b));(b=AdCall.modelSegs())&&c.push(b);return c.join("|")}
(function(){AMOAD_API_PATH="/n/v1/?";Node.setGlobal("__amoadNativeCallback",callBack);var a=function(b,c){var f=new AdTagOption(c),g=MultiAd.getItem(b);g.arg?AdEmbedded.createAd(b,c,g.arg,f):g.loader?g.loader.addEventListener("load",function(){a(b,c)},!1):(f=getRequestURI(b,c,f))&&function(a,b,c){g.loader=AdCall.buildAdCallJsonP(c,Node.create);AdTagStatus.setSent(b);Node.appendHeadChild(g.loader)}(b,c,f)},c=AdTagStatus.findNone(AdTag.amoadFrames(document.body));if(c){var b=AdTag.getSid(c);b&&(AdTagStatus.setScanned(c),
a(b,c))}})();})();
